# Generated by Django 6.0.6 on 2026-06-26 12:27

import django.db.models.deletion
from django.db import migrations, models


def convert_legacy_visit_types(apps, schema_editor):
    """Map old OPD/Emergency/Inpatient rows to the new 'New Visit' type."""
    Visit = apps.get_model('core', 'Visit')
    Visit.objects.filter(
        visit_type__in=['OPD', 'Emergency', 'Inpatient']
    ).update(visit_type='New Visit')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_patient_blood_group_patient_is_active_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='previous_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='core.visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('New Visit', 'New Visit'), ('Revisit', 'Revisit'), ('Repayment', 'Repayment')], max_length=20),
        ),
        migrations.RunPython(convert_legacy_visit_types, migrations.RunPython.noop),
    ]
