# Generated by Django 6.0.6 on 2026-06-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_medication_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('store_type', models.CharField(choices=[('or', 'Operating Room (OR)'), ('ward', 'Inpatient Ward'), ('er', 'Emergency Department'), ('pod', 'Post-Operative Department'), ('icu', 'Intensive Care Unit'), ('opd', 'Outpatient Department'), ('labour', 'Labour & Delivery'), ('pediatric', 'Pediatric Ward'), ('nicu', 'Neonatal ICU'), ('surgical', 'Surgical Ward'), ('medical', 'Medical Ward'), ('psychiatric', 'Psychiatric Ward'), ('oncology', 'Oncology Ward'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['store_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='hmspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_queue', 'Can manage patient queue'), ('perform_triage', 'Can perform triage assessment'), ('write_clinical_note', 'Can write clinical notes'), ('read_clinical_note', 'Can read clinical notes'), ('write_nursing_note', 'Can write nursing notes'), ('read_nursing_note', 'Can read nursing notes'), ('record_vital_signs', 'Can record vital signs'), ('read_vital_signs', 'Can read vital signs'), ('write_care_plan', 'Can write care plans'), ('read_care_plan', 'Can read care plans'), ('write_diagnosis', 'Can write diagnosis'), ('read_diagnosis', 'Can read diagnosis records'), ('write_prescription', 'Can write prescriptions'), ('read_prescription', 'Can read prescriptions'), ('request_lab_test', 'Can request laboratory tests'), ('read_lab_request', 'Can read lab requests'), ('process_lab_test', 'Can process lab tests / enter results'), ('write_lab_result', 'Can write lab results'), ('read_lab_result', 'Can read lab results'), ('request_imaging', 'Can request imaging studies'), ('read_imaging_request', 'Can read imaging requests'), ('process_imaging', 'Can process imaging studies'), ('write_imaging_report', 'Can write imaging reports'), ('read_imaging_report', 'Can read imaging reports'), ('write_anesthesia_record', 'Can write anesthesia records'), ('read_anesthesia_record', 'Can read anesthesia records'), ('read_billing', 'Can read billing records'), ('create_invoice', 'Can create invoices'), ('manage_billing', 'Can manage all billing records'), ('process_payment', 'Can process payments'), ('read_financial_report', 'Can read financial reports'), ('read_medication_inventory', 'Can read medication inventory'), ('manage_medication', 'Can manage medication inventory'), ('dispense_medication', 'Can dispense medications'), ('read_prescription_for_dispensing', 'Can read prescriptions for dispensing'), ('process_pharmacy_sale', 'Can process pharmacy sales'), ('view_dept_inventory', 'Can view department store inventory'), ('manage_dept_stores', 'Can create and edit department stores'), ('request_medication_transfer', 'Can request medication transfers'), ('approve_medication_transfer', 'Can approve / fulfill medication transfers'), ('record_dept_usage', 'Can record medication usage in department'), ('view_dept_reports', 'Can view department pharmacy reports'), ('manage_med_catalog', 'Can manage medication catalog'), ('receive_stock', 'Can receive stock / create batches'), ('manage_suppliers', 'Can manage suppliers'), ('view_inv_reports', 'Can view inventory reports'), ('export_inv_reports', 'Can export inventory reports'), ('read_inventory', 'Can read store inventory'), ('manage_inventory', 'Can manage store inventory'), ('create_purchase_order', 'Can create purchase orders'), ('approve_purchase_order', 'Can approve purchase orders'), ('read_employee', 'Can read employee records'), ('manage_employees', 'Can manage employee records'), ('manage_attendance', 'Can manage attendance'), ('manage_payroll', 'Can manage payroll'), ('read_appointment', 'Can read appointments'), ('manage_appointments', 'Can manage appointments'), ('read_clinical_reports', 'Can read clinical reports'), ('read_department_reports', 'Can read department reports'), ('manage_users', 'Can manage system users'), ('manage_roles', 'Can manage roles and permissions'), ('system_configuration', 'Can access system configuration'), ('read_audit_log', 'Can read audit logs'), ('manage_departments', 'Can manage departments')], 'verbose_name': 'HMS Permission', 'verbose_name_plural': 'HMS Permissions'},
        ),
        migrations.CreateModel(
            name='DepartmentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.IntegerField(default=0)),
                ('minimum_quantity', models.IntegerField(default=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_stocks', to='core.medication')),
                ('department_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.departmentstore')),
            ],
            options={
                'unique_together': {('department_store', 'medication')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentStockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('quantity_available', models.IntegerField(default=0)),
                ('received_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('dept_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.departmentstock')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicationbatch')),
            ],
            options={
                'ordering': ['expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=20, unique=True)),
                ('transfer_type', models.CharField(choices=[('pharm_to_dept', 'Pharmacy → Department'), ('dept_to_pharm', 'Department → Pharmacy'), ('dept_to_dept', 'Department → Department')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Receipt'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dest_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='core.departmentstore')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_prepared', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
                ('source_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfers', to='core.departmentstore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('quantity_transferred', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dept_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departmentstockbatch')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medication')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicationbatch')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.departmenttransfer')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_number', models.CharField(max_length=20, unique=True)),
                ('quantity_used', models.IntegerField()),
                ('usage_type', models.CharField(choices=[('administration', 'Patient Administration'), ('emergency', 'Emergency Use'), ('surgical', 'Surgical Procedure'), ('wastage', 'Wastage / Spoilage'), ('expired', 'Expired Disposal'), ('returned', 'Returned to Pharmacy'), ('adjustment', 'Stock Adjustment')], max_length=20)),
                ('usage_date', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='core.departmentstore')),
                ('dept_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departmentstockbatch')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_usages', to='core.medication')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient')),
                ('responsible_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_usages_performed', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.visit')),
            ],
            options={
                'ordering': ['-usage_date'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('partial', 'Partially Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=15)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('fulfillment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requesting_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='core.departmentstore')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddField(
            model_name='departmenttransfer',
            name='transfer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='core.transferrequest'),
        ),
        migrations.CreateModel(
            name='TransferRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField()),
                ('quantity_approved', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medication')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.transferrequest')),
            ],
        ),
    ]
