# Generated by Django 6.0.6 on 2026-06-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dept_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_type',
            field=models.CharField(choices=[('administration', 'Administration'), ('clinical', 'Medical / Clinical'), ('nursing', 'Nursing'), ('emergency', 'Emergency'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('or', 'Operating Room'), ('ward', 'Ward / Inpatient'), ('icu', 'Intensive Care Unit'), ('opd', 'Outpatient'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('store', 'Store / Inventory'), ('maternity', 'Maternity / Labour'), ('pediatrics', 'Pediatrics'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_level',
            field=models.CharField(choices=[('read_only', 'Read Only'), ('standard', 'Standard'), ('elevated', 'Elevated'), ('full', 'Full Access')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
