# Generated by Django 6.0.6 on 2026-06-28 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_billing_cash_credit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject'), ('issue', 'Issue'), ('receive', 'Receive'), ('transfer', 'Transfer'), ('adjust', 'Adjust'), ('dispose', 'Dispose'), ('payment', 'Payment'), ('refund', 'Refund'), ('cancel', 'Cancel'), ('waive', 'Waive'), ('dispense', 'Dispense'), ('return', 'Return'), ('access', 'Record Access'), ('password_change', 'Password Change'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('open_session', 'Open Session'), ('close_session', 'Close Session')], db_index=True, max_length=30)),
                ('module', models.CharField(choices=[('patient', 'Patient'), ('appointment', 'Appointment'), ('visit', 'Visit'), ('doctor', 'Doctor / Clinical'), ('nursing', 'Nursing'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('med_inventory', 'Medication Inventory'), ('dept_pharmacy', 'Dept Pharmacy'), ('inventory', 'Store & Inventory'), ('billing', 'Billing'), ('payment', 'Payment'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('admin', 'Administration'), ('auth', 'Authentication'), ('user', 'User Management'), ('anesthesia', 'Anesthesia'), ('queue', 'Queue / Triage')], db_index=True, max_length=30)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['module', 'timestamp'], name='core_auditl_module_3b671b_idx'), models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'), models.Index(fields=['action', 'module'], name='core_auditl_action_f9c578_idx'), models.Index(fields=['severity', 'timestamp'], name='core_auditl_severit_4032b9_idx')],
            },
        ),
    ]
