# Generated by Django 6.0.6 on 2026-06-29 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_surgery_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_type', models.CharField(choices=[('regular', 'Regular Discharge'), ('ama', 'Against Medical Advice'), ('transfer', 'Transfer to Another Facility'), ('death', 'Death'), ('follow_up', 'Discharged with Follow-up')], default='regular', max_length=20)),
                ('discharge_condition', models.CharField(choices=[('improved', 'Improved'), ('stable', 'Stable'), ('unchanged', 'Unchanged'), ('deteriorated', 'Deteriorated'), ('deceased', 'Deceased')], default='improved', max_length=20)),
                ('final_diagnosis', models.TextField()),
                ('secondary_diagnoses', models.TextField(blank=True)),
                ('procedures_performed', models.TextField(blank=True)),
                ('hospital_course', models.TextField(blank=True, help_text='Brief summary of treatment during visit')),
                ('treatment_summary', models.TextField(blank=True)),
                ('investigations_summary', models.TextField(blank=True)),
                ('discharge_instructions', models.TextField(blank=True)),
                ('diet_instructions', models.TextField(blank=True)),
                ('activity_restrictions', models.TextField(blank=True)),
                ('wound_care', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('discharge_medications', models.TextField(blank=True, help_text='List of medications prescribed at discharge')),
                ('transfer_facility', models.CharField(blank=True, max_length=200)),
                ('transfer_reason', models.TextField(blank=True)),
                ('authored_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discharge Summary',
                'verbose_name_plural': 'Discharge Summaries',
            },
        ),
        migrations.CreateModel(
            name='VisitJourneyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('payment', 'Payment Event'), ('clinical', 'Clinical Event'), ('order', 'Order Placed'), ('result', 'Result Received'), ('discharge', 'Discharge Event'), ('admin', 'Administrative'), ('system', 'System Event')], default='system', max_length=20)),
                ('status_before', models.CharField(blank=True, max_length=30)),
                ('status_after', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Journey Event',
                'verbose_name_plural': 'Journey Events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='hmspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_queue', 'Can manage patient queue'), ('perform_triage', 'Can perform triage assessment'), ('write_clinical_note', 'Can write clinical notes'), ('read_clinical_note', 'Can read clinical notes'), ('write_nursing_note', 'Can write nursing notes'), ('read_nursing_note', 'Can read nursing notes'), ('record_vital_signs', 'Can record vital signs'), ('read_vital_signs', 'Can read vital signs'), ('write_care_plan', 'Can write care plans'), ('read_care_plan', 'Can read care plans'), ('write_diagnosis', 'Can write diagnosis'), ('read_diagnosis', 'Can read diagnosis records'), ('write_prescription', 'Can write prescriptions'), ('read_prescription', 'Can read prescriptions'), ('request_lab_test', 'Can request laboratory tests'), ('read_lab_request', 'Can read lab requests'), ('process_lab_test', 'Can process lab tests / enter results'), ('write_lab_result', 'Can write lab results'), ('read_lab_result', 'Can read lab results'), ('request_imaging', 'Can request imaging studies'), ('read_imaging_request', 'Can read imaging requests'), ('process_imaging', 'Can process imaging studies'), ('write_imaging_report', 'Can write imaging reports'), ('read_imaging_report', 'Can read imaging reports'), ('write_anesthesia_record', 'Can write anesthesia records'), ('read_anesthesia_record', 'Can read anesthesia records'), ('read_billing', 'Can read billing records'), ('create_invoice', 'Can create invoices'), ('manage_billing', 'Can manage all billing records'), ('process_payment', 'Can process payments'), ('approve_credit_invoice', 'Can approve credit invoices'), ('manage_cash_sessions', 'Can open and close cash sessions'), ('read_financial_report', 'Can read financial reports'), ('read_medication_inventory', 'Can read medication inventory'), ('manage_medication', 'Can manage medication inventory'), ('dispense_medication', 'Can dispense medications'), ('read_prescription_for_dispensing', 'Can read prescriptions for dispensing'), ('process_pharmacy_sale', 'Can process pharmacy sales'), ('view_dept_inventory', 'Can view department store inventory'), ('manage_dept_stores', 'Can create and edit department stores'), ('request_medication_transfer', 'Can request medication transfers'), ('approve_medication_transfer', 'Can approve / fulfill medication transfers'), ('record_dept_usage', 'Can record medication usage in department'), ('view_dept_reports', 'Can view department pharmacy reports'), ('manage_med_catalog', 'Can manage medication catalog'), ('receive_stock', 'Can receive stock / create batches'), ('manage_suppliers', 'Can manage suppliers'), ('view_inv_reports', 'Can view inventory reports'), ('export_inv_reports', 'Can export inventory reports'), ('read_inventory', 'Can read store inventory'), ('manage_inventory', 'Can manage store inventory'), ('create_purchase_order', 'Can create purchase orders'), ('approve_purchase_order', 'Can approve purchase orders'), ('read_employee', 'Can read employee records'), ('manage_employees', 'Can manage employee records'), ('manage_attendance', 'Can manage attendance'), ('manage_payroll', 'Can manage payroll'), ('read_appointment', 'Can read appointments'), ('manage_appointments', 'Can manage appointments'), ('read_clinical_reports', 'Can read clinical reports'), ('read_department_reports', 'Can read department reports'), ('manage_users', 'Can manage system users'), ('manage_roles', 'Can manage roles and permissions'), ('system_configuration', 'Can access system configuration'), ('read_audit_log', 'Can read audit logs'), ('manage_departments', 'Can manage departments'), ('view_patient_flow', 'Can view the patient flow dashboard'), ('manage_patient_flow', 'Can update patient journey status'), ('manage_discharge', 'Can create and manage discharge summaries'), ('view_dept_worklist', 'Can view department work list'), ('manage_procedure_master', 'Can manage procedure/surgery master list'), ('order_surgery', 'Can create and manage surgery orders'), ('approve_surgery_order', 'Can approve or reject surgery orders'), ('manage_or_schedule', 'Can manage OR schedule and room assignments'), ('write_surgery_anesthesia', 'Can write surgery anesthesia records'), ('read_surgery', 'Can read surgery orders and records'), ('write_operative_note', 'Can write operative notes'), ('manage_surgery_consumables', 'Can manage surgery consumables and supplies'), ('generate_surgery_billing', 'Can generate billing from surgery orders'), ('read_surgery_reports', 'Can read surgery reports')], 'verbose_name': 'HMS Permission', 'verbose_name_plural': 'HMS Permissions'},
        ),
        migrations.AddField(
            model_name='visit',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('visit_created', 'Visit Created'), ('waiting_payment', 'Waiting for Payment'), ('payment_completed', 'Payment Completed'), ('waiting_doctor', 'Waiting for Doctor'), ('consultation_started', 'Consultation Started'), ('investigation_ordered', 'Investigation Ordered'), ('investigation_completed', 'Investigation Completed'), ('treatment_started', 'Treatment Started'), ('procedure_scheduled', 'Procedure / Surgery Scheduled'), ('completed', 'Consultation Completed'), ('discharged', 'Discharged'), ('follow_up_required', 'Follow-up Required')], db_index=True, default='visit_created', max_length=30),
        ),
        migrations.AddField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', '-created_at'], name='core_visit_status_558ccb_idx'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='authored_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharge_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='follow_up_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_follow_ups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summary', to='core.visit'),
        ),
        migrations.AddField(
            model_name='visitjourneyevent',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitjourneyevent',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_events', to='core.visit'),
        ),
    ]
