# Generated by Django 6.0.6 on 2026-06-29 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_patient_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Sent to Pharmacy', 'Sent to Pharmacy'), ('Under Review', 'Under Review'), ('Ready to Dispense', 'Ready to Dispense'), ('Dispensed', 'Dispensed'), ('Partially Dispensed', 'Partially Dispensed'), ('Cancelled', 'Cancelled')], default='Created', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('sent_to_pharmacy_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='core.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_verified', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='core.visit')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('Oral', 'Oral'), ('Intravenous', 'Intravenous (IV)'), ('Intramuscular', 'Intramuscular (IM)'), ('Subcutaneous', 'Subcutaneous (SC)'), ('Topical', 'Topical'), ('Inhalation', 'Inhalation'), ('Sublingual', 'Sublingual'), ('Rectal', 'Rectal'), ('Other', 'Other')], default='Oral', max_length=20)),
                ('frequency', models.CharField(choices=[('Once daily', 'Once daily (OD)'), ('Twice daily', 'Twice daily (BD)'), ('Three times daily', 'Three times daily (TDS)'), ('Four times daily', 'Four times daily (QID)'), ('Every 8 hours', 'Every 8 hours'), ('Every 12 hours', 'Every 12 hours'), ('As needed', 'As needed (PRN)'), ('Immediately', 'Immediately (STAT)'), ('At bedtime', 'At bedtime (nocte)')], default='Twice daily', max_length=30)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('meal_instruction', models.CharField(blank=True, choices=[('Before meals', 'Before meals'), ('After meals', 'After meals'), ('With food', 'With food'), ('Empty stomach', 'On empty stomach'), ('With plenty of water', 'With plenty of water'), ('See notes', 'See notes')], max_length=30)),
                ('special_instructions', models.TextField(blank=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Dispensed', 'Dispensed'), ('Partially Dispensed', 'Partially Dispensed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=25)),
                ('quantity_dispensed', models.PositiveIntegerField(default=0)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='core.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'ordering': ['order_index', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MAREntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('dose_given', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Given', 'Given'), ('Missed', 'Missed'), ('Held', 'Held'), ('Refused', 'Refused')], default='Scheduled', max_length=15)),
                ('patient_response', models.TextField(blank=True)),
                ('reason_missed', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mar_entries', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_entries', to='core.visit')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_entries', to='core.prescriptionitem')),
            ],
            options={
                'verbose_name': 'MAR Entry',
                'verbose_name_plural': 'MAR Entries',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='RxDispenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rx_dispense_records', to=settings.AUTH_USER_MODEL)),
                ('medication_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rx_dispense_records', to='core.medicationbatch')),
                ('pharmacy_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rx_dispense_records', to='core.pharmacystock')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_records', to='core.prescriptionitem')),
            ],
            options={
                'verbose_name': 'Dispense Record',
                'ordering': ['-dispensed_at'],
            },
        ),
    ]
