# Generated by Django 6.0.6 on 2026-06-29 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pharmacy_pos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rxdispenserecord',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rxdispenserecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rx_dispense_records_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rxdispenserecord',
            name='stock_confirmed',
            field=models.BooleanField(default=True, help_text='True once inventory has been physically deducted after payment.'),
        ),
        migrations.AlterField(
            model_name='pharmacysale',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Payment'), ('Dispensed', 'Dispensed'), ('Credit', 'Dispensed on Credit'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Billed', 'Sent to Billing'), ('Dispensed', 'Dispensed'), ('Partial', 'Partially Dispensed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=25),
        ),
    ]
