# Generated by Django 6.0.6 on 2026-07-01 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_inventory_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('Leave', 'Annual / Sick Leave'), ('Holiday', 'Public Holiday'), ('Conference', 'Conference / Training'), ('Modified', 'Modified Hours'), ('Other', 'Other')], default='Leave', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doctor Schedule Exception',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OperatingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('room_type', models.CharField(choices=[('General', 'General Surgery'), ('Cardiac', 'Cardiac / Cardiothoracic'), ('Orthopedic', 'Orthopedic'), ('Neurosurgery', 'Neurosurgery'), ('Ophthalmic', 'Ophthalmology'), ('Obstetric', 'Obstetrics / Gynecology'), ('ENT', 'ENT'), ('Urology', 'Urology'), ('Laparoscopic', 'Laparoscopic'), ('Other', 'Other')], default='General', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('location_detail', models.CharField(blank=True, max_length=100)),
                ('capacity_hours', models.PositiveIntegerField(default=8, help_text='Available hours per day')),
                ('equipment_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Operating Room',
                'verbose_name_plural': 'Operating Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ORSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_number', models.CharField(blank=True, max_length=25, unique=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Scheduled', 'Scheduled'), ('Patient Prepared', 'Patient Prepared'), ('In OR', 'In OR'), ('Surgery Started', 'Surgery Started'), ('Surgery Completed', 'Surgery Completed'), ('Cancelled', 'Cancelled'), ('Postponed', 'Postponed')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('postpone_reason', models.TextField(blank=True)),
                ('patient_prepared_at', models.DateTimeField(blank=True, null=True)),
                ('in_or_at', models.DateTimeField(blank=True, null=True)),
                ('surgery_started_at', models.DateTimeField(blank=True, null=True)),
                ('surgery_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OR Schedule',
                'verbose_name_plural': 'OR Schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ORScheduleStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=25)),
                ('to_status', models.CharField(max_length=25)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=25, unique=True)),
                ('diagnosis', models.TextField()),
                ('procedure_name', models.CharField(max_length=200)),
                ('procedure_code', models.CharField(blank=True, max_length=50)),
                ('anesthesia_type', models.CharField(choices=[('General', 'General Anesthesia'), ('Spinal', 'Spinal'), ('Epidural', 'Epidural'), ('Local', 'Local Anesthesia'), ('Regional', 'Regional Block'), ('MAC', 'Monitored Anesthesia Care'), ('Other', 'Other')], default='General', max_length=20)),
                ('priority', models.CharField(choices=[('Emergency', 'Emergency'), ('Urgent', 'Urgent'), ('Elective', 'Elective')], default='Elective', max_length=15)),
                ('admission_status', models.CharField(choices=[('Outpatient', 'Outpatient'), ('Inpatient', 'Inpatient'), ('Emergency', 'Emergency')], default='Inpatient', max_length=15)),
                ('expected_duration', models.PositiveIntegerField(default=60, help_text='Expected duration in minutes')),
                ('required_equipment', models.TextField(blank=True)),
                ('required_implants', models.TextField(blank=True)),
                ('preop_notes', models.TextField(blank=True)),
                ('anesthesia_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Requested', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Surgery Request',
                'verbose_name_plural': 'Surgery Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='hmspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_queue', 'Can manage patient queue'), ('perform_triage', 'Can perform triage assessment'), ('write_clinical_note', 'Can write clinical notes'), ('read_clinical_note', 'Can read clinical notes'), ('write_nursing_note', 'Can write nursing notes'), ('read_nursing_note', 'Can read nursing notes'), ('record_vital_signs', 'Can record vital signs'), ('read_vital_signs', 'Can read vital signs'), ('write_care_plan', 'Can write care plans'), ('read_care_plan', 'Can read care plans'), ('write_diagnosis', 'Can write diagnosis'), ('read_diagnosis', 'Can read diagnosis records'), ('write_prescription', 'Can write prescriptions'), ('read_prescription', 'Can read prescriptions'), ('request_lab_test', 'Can request laboratory tests'), ('read_lab_request', 'Can read lab requests'), ('process_lab_test', 'Can process lab tests / enter results'), ('write_lab_result', 'Can write lab results'), ('read_lab_result', 'Can read lab results'), ('collect_lab_sample', 'Can record sample collection'), ('release_lab_result', 'Can release lab results to patient'), ('manage_lab_services', 'Can manage lab service catalogue and pricing'), ('lab_reception', 'Can access lab reception / payment verification'), ('request_imaging', 'Can request imaging studies'), ('read_imaging_request', 'Can read imaging requests'), ('process_imaging', 'Can process imaging studies'), ('write_imaging_report', 'Can write imaging reports'), ('read_imaging_report', 'Can read imaging reports'), ('write_anesthesia_record', 'Can write anesthesia records'), ('read_anesthesia_record', 'Can read anesthesia records'), ('read_billing', 'Can read billing records'), ('create_invoice', 'Can create invoices'), ('manage_billing', 'Can manage all billing records'), ('process_payment', 'Can process payments'), ('approve_credit_invoice', 'Can approve credit invoices'), ('manage_cash_sessions', 'Can open and close cash sessions'), ('read_financial_report', 'Can read financial reports'), ('read_medication_inventory', 'Can read medication inventory'), ('manage_medication', 'Can manage medication inventory'), ('dispense_medication', 'Can dispense medications'), ('read_prescription_for_dispensing', 'Can read prescriptions for dispensing'), ('process_pharmacy_sale', 'Can process pharmacy sales'), ('approve_pharmacy_discount', 'Can approve pharmacy discounts'), ('approve_credit_sale', 'Can approve credit pharmacy sales'), ('manage_pharmacy_returns', 'Can process pharmacy returns/refunds'), ('read_pharmacy_reports', 'Can view pharmacy sales reports'), ('view_dept_inventory', 'Can view department store inventory'), ('manage_dept_stores', 'Can create and edit department stores'), ('request_medication_transfer', 'Can request medication transfers'), ('approve_medication_transfer', 'Can approve / fulfill medication transfers'), ('record_dept_usage', 'Can record medication usage in department'), ('view_dept_reports', 'Can view department pharmacy reports'), ('manage_med_catalog', 'Can manage medication catalog'), ('receive_stock', 'Can receive stock / create batches'), ('manage_suppliers', 'Can manage suppliers'), ('view_inv_reports', 'Can view inventory reports'), ('export_inv_reports', 'Can export inventory reports'), ('read_inventory', 'Can read store inventory'), ('manage_inventory', 'Can manage store inventory'), ('create_purchase_order', 'Can create purchase orders'), ('approve_purchase_order', 'Can approve purchase orders'), ('create_purchase_request', 'Can create purchase requests'), ('approve_purchase_request', 'Can approve purchase requests'), ('issue_inventory', 'Can issue items from store'), ('manage_inventory_batches', 'Can receive and manage inventory batches'), ('manage_equipment_assets', 'Can manage equipment and asset records'), ('perform_stock_count', 'Can perform physical stock count'), ('approve_stock_count', 'Can approve stock count results'), ('view_store_reports', 'Can view store reports'), ('export_store_reports', 'Can export store reports'), ('read_employee', 'Can read employee records'), ('manage_employees', 'Can manage employee records'), ('manage_attendance', 'Can manage attendance'), ('manage_payroll', 'Can manage payroll'), ('read_appointment', 'Can read appointments'), ('manage_appointments', 'Can manage appointments'), ('manage_doctor_availability', 'Can manage doctor schedules and availability'), ('view_appointment_reports', 'Can view appointment reports'), ('export_appointment_reports', 'Can export appointment reports'), ('read_clinical_reports', 'Can read clinical reports'), ('read_department_reports', 'Can read department reports'), ('manage_users', 'Can manage system users'), ('manage_roles', 'Can manage roles and permissions'), ('system_configuration', 'Can access system configuration'), ('read_audit_log', 'Can read audit logs'), ('manage_departments', 'Can manage departments'), ('view_patient_flow', 'Can view the patient flow dashboard'), ('manage_patient_flow', 'Can update patient journey status'), ('manage_discharge', 'Can create and manage discharge summaries'), ('view_dept_worklist', 'Can view department work list'), ('manage_procedure_master', 'Can manage procedure/surgery master list'), ('order_surgery', 'Can create and manage surgery orders'), ('approve_surgery_order', 'Can approve or reject surgery orders'), ('manage_or_schedule', 'Can manage OR schedule and room assignments'), ('write_surgery_anesthesia', 'Can write surgery anesthesia records'), ('read_surgery', 'Can read surgery orders and records'), ('write_operative_note', 'Can write operative notes'), ('manage_surgery_consumables', 'Can manage surgery consumables and supplies'), ('generate_surgery_billing', 'Can generate billing from surgery orders'), ('read_surgery_reports', 'Can read surgery reports')], 'verbose_name': 'HMS Permission', 'verbose_name_plural': 'HMS Permissions'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Normal', max_length=15),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason_for_visit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='referral_source',
            field=models.CharField(choices=[('Reception', 'Reception / Walk-in'), ('Call Center', 'Call Center'), ('Referral', 'Doctor Referral'), ('Online', 'Online / Portal'), ('Other', 'Other')], default='Reception', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='core.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('New Visit', 'New Visit'), ('Revisit', 'Revisit'), ('Follow-up', 'Follow-up')], default='New Visit', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Checked In', 'Checked In'), ('Waiting', 'Waiting'), ('In Consultation', 'In Consultation'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('No Show', 'No Show'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled')], default='Scheduled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='core_appoin_status_6824f8_idx'),
        ),
        migrations.AddField(
            model_name='appointmentstatuslog',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentstatuslog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorscheduleexception',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_exceptions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorscheduleexception',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='orschedule',
            name='anesthetist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='or_schedules_anesthetist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orschedule',
            name='assistant_surgeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='or_schedules_assistant', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='orschedule',
            name='circulating_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='or_schedules_circulating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orschedule',
            name='operating_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='core.operatingroom'),
        ),
        migrations.AddField(
            model_name='orschedule',
            name='primary_surgeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='or_schedules_primary', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='orschedule',
            name='scheduled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='or_schedules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orschedule',
            name='scrub_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='or_schedules_scrub', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orschedulestatuslog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='or_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orschedulestatuslog',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.orschedule'),
        ),
        migrations.AddField(
            model_name='surgeryrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgeryrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgery_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgeryrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surgery_requests', to='core.department'),
        ),
        migrations.AddField(
            model_name='surgeryrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgery_requests', to='core.patient'),
        ),
        migrations.AddField(
            model_name='surgeryrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgery_requests_created', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='orschedule',
            name='surgery_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='or_schedule', to='core.surgeryrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorscheduleexception',
            unique_together={('doctor', 'date')},
        ),
        migrations.AddIndex(
            model_name='surgeryrequest',
            index=models.Index(fields=['status', 'priority'], name='core_surger_status_b2d267_idx'),
        ),
        migrations.AddIndex(
            model_name='surgeryrequest',
            index=models.Index(fields=['patient'], name='core_surger_patient_ee1801_idx'),
        ),
        migrations.AddIndex(
            model_name='orschedule',
            index=models.Index(fields=['date', 'operating_room'], name='core_orsche_date_fe2d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='orschedule',
            index=models.Index(fields=['date', 'primary_surgeon'], name='core_orsche_date_bc56f2_idx'),
        ),
        migrations.AddIndex(
            model_name='orschedule',
            index=models.Index(fields=['status'], name='core_orsche_status_69a0fd_idx'),
        ),
    ]
