# Generated by Django 6.0.6 on 2026-07-01 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_appointment_and_or_scheduling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabServicePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('standard', 'Standard'), ('insurance', 'Insurance'), ('corporate', 'Corporate'), ('emergency', 'Emergency')], default='standard', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lab Service Price History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='hmspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_queue', 'Can manage patient queue'), ('perform_triage', 'Can perform triage assessment'), ('write_clinical_note', 'Can write clinical notes'), ('read_clinical_note', 'Can read clinical notes'), ('write_nursing_note', 'Can write nursing notes'), ('read_nursing_note', 'Can read nursing notes'), ('record_vital_signs', 'Can record vital signs'), ('read_vital_signs', 'Can read vital signs'), ('write_care_plan', 'Can write care plans'), ('read_care_plan', 'Can read care plans'), ('write_diagnosis', 'Can write diagnosis'), ('read_diagnosis', 'Can read diagnosis records'), ('write_prescription', 'Can write prescriptions'), ('read_prescription', 'Can read prescriptions'), ('request_lab_test', 'Can request laboratory tests'), ('read_lab_request', 'Can read lab requests'), ('process_lab_test', 'Can process lab tests / enter results'), ('write_lab_result', 'Can write lab results'), ('read_lab_result', 'Can read lab results'), ('collect_lab_sample', 'Can record sample collection'), ('release_lab_result', 'Can release lab results to patient'), ('manage_lab_services', 'Can manage lab service catalogue and pricing'), ('view_lab_reports', 'Can view laboratory management reports'), ('lab_reception', 'Can access lab reception / payment verification'), ('request_imaging', 'Can request imaging studies'), ('read_imaging_request', 'Can read imaging requests'), ('process_imaging', 'Can process imaging studies'), ('write_imaging_report', 'Can write imaging reports'), ('read_imaging_report', 'Can read imaging reports'), ('write_anesthesia_record', 'Can write anesthesia records'), ('read_anesthesia_record', 'Can read anesthesia records'), ('read_billing', 'Can read billing records'), ('create_invoice', 'Can create invoices'), ('manage_billing', 'Can manage all billing records'), ('process_payment', 'Can process payments'), ('approve_credit_invoice', 'Can approve credit invoices'), ('manage_cash_sessions', 'Can open and close cash sessions'), ('read_financial_report', 'Can read financial reports'), ('read_medication_inventory', 'Can read medication inventory'), ('manage_medication', 'Can manage medication inventory'), ('dispense_medication', 'Can dispense medications'), ('read_prescription_for_dispensing', 'Can read prescriptions for dispensing'), ('process_pharmacy_sale', 'Can process pharmacy sales'), ('approve_pharmacy_discount', 'Can approve pharmacy discounts'), ('approve_credit_sale', 'Can approve credit pharmacy sales'), ('manage_pharmacy_returns', 'Can process pharmacy returns/refunds'), ('read_pharmacy_reports', 'Can view pharmacy sales reports'), ('view_dept_inventory', 'Can view department store inventory'), ('manage_dept_stores', 'Can create and edit department stores'), ('request_medication_transfer', 'Can request medication transfers'), ('approve_medication_transfer', 'Can approve / fulfill medication transfers'), ('record_dept_usage', 'Can record medication usage in department'), ('view_dept_reports', 'Can view department pharmacy reports'), ('manage_med_catalog', 'Can manage medication catalog'), ('receive_stock', 'Can receive stock / create batches'), ('manage_suppliers', 'Can manage suppliers'), ('view_inv_reports', 'Can view inventory reports'), ('export_inv_reports', 'Can export inventory reports'), ('read_inventory', 'Can read store inventory'), ('manage_inventory', 'Can manage store inventory'), ('create_purchase_order', 'Can create purchase orders'), ('approve_purchase_order', 'Can approve purchase orders'), ('create_purchase_request', 'Can create purchase requests'), ('approve_purchase_request', 'Can approve purchase requests'), ('issue_inventory', 'Can issue items from store'), ('manage_inventory_batches', 'Can receive and manage inventory batches'), ('manage_equipment_assets', 'Can manage equipment and asset records'), ('perform_stock_count', 'Can perform physical stock count'), ('approve_stock_count', 'Can approve stock count results'), ('view_store_reports', 'Can view store reports'), ('export_store_reports', 'Can export store reports'), ('read_employee', 'Can read employee records'), ('manage_employees', 'Can manage employee records'), ('manage_attendance', 'Can manage attendance'), ('manage_payroll', 'Can manage payroll'), ('read_appointment', 'Can read appointments'), ('manage_appointments', 'Can manage appointments'), ('manage_doctor_availability', 'Can manage doctor schedules and availability'), ('view_appointment_reports', 'Can view appointment reports'), ('export_appointment_reports', 'Can export appointment reports'), ('read_clinical_reports', 'Can read clinical reports'), ('read_department_reports', 'Can read department reports'), ('manage_users', 'Can manage system users'), ('manage_roles', 'Can manage roles and permissions'), ('system_configuration', 'Can access system configuration'), ('read_audit_log', 'Can read audit logs'), ('manage_departments', 'Can manage departments'), ('view_patient_flow', 'Can view the patient flow dashboard'), ('manage_patient_flow', 'Can update patient journey status'), ('manage_discharge', 'Can create and manage discharge summaries'), ('view_dept_worklist', 'Can view department work list'), ('manage_procedure_master', 'Can manage procedure/surgery master list'), ('order_surgery', 'Can create and manage surgery orders'), ('approve_surgery_order', 'Can approve or reject surgery orders'), ('manage_or_schedule', 'Can manage OR schedule and room assignments'), ('write_surgery_anesthesia', 'Can write surgery anesthesia records'), ('read_surgery', 'Can read surgery orders and records'), ('write_operative_note', 'Can write operative notes'), ('manage_surgery_consumables', 'Can manage surgery consumables and supplies'), ('generate_surgery_billing', 'Can generate billing from surgery orders'), ('read_surgery_reports', 'Can read surgery reports')], 'verbose_name': 'HMS Permission', 'verbose_name_plural': 'HMS Permissions'},
        ),
        migrations.AddField(
            model_name='labservice',
            name='container',
            field=models.CharField(blank=True, help_text='e.g. EDTA tube, Plain tube', max_length=100),
        ),
        migrations.AddField(
            model_name='labservice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_services_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labservice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labservice',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated search terms e.g. blood count, hemoglobin, CBC'),
        ),
        migrations.AddField(
            model_name='labservice',
            name='short_name',
            field=models.CharField(blank=True, help_text='Abbreviation e.g. CBC, LFT, TFT', max_length=30),
        ),
        migrations.AddIndex(
            model_name='labservice',
            index=models.Index(fields=['is_active', 'section'], name='core_labser_is_acti_60b787_idx'),
        ),
        migrations.AddField(
            model_name='labservicepricehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_price_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labservicepricehistory',
            name='lab_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.labservice'),
        ),
    ]
