# Generated by Django 6.0.6 on 2026-07-01 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_lab_service_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='billing_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prescription',
            name='billing_status',
            field=models.CharField(choices=[('not_billed', 'Not Billed'), ('pending_payment', 'Pending Payment'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('credit_approved', 'Credit Approved'), ('waived', 'Waived'), ('cancelled', 'Cancelled')], default='not_billed', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='credit_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='credit_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_approved_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='credit_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='invoice_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_item', to='core.invoiceitem'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Sent to Pharmacy', 'Sent to Pharmacy'), ('Under Review', 'Under Review'), ('Ready to Dispense', 'Ready to Dispense'), ('Waiting Payment', 'Waiting for Payment'), ('Dispensed', 'Dispensed'), ('Partially Dispensed', 'Partially Dispensed'), ('Cancelled', 'Cancelled')], default='Created', max_length=25),
        ),
    ]
