# Generated by Django 6.0.6 on 2026-07-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_imaging_medication_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationorder',
            name='medication',
        ),
        migrations.AddField(
            model_name='medicationorder',
            name='pharmacy_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_orders', to='core.pharmacystock'),
        ),
    ]
