# Generated by Django 6.0.6 on 2026-07-05 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_medication_order_pharmacy_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='medication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_stock_link', to='core.medication'),
        ),
    ]
