# Generated by Django 6.0.6 on 2026-07-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_pharmacy_stock_medication_bridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryconsumable',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_consumables', to='core.inventoryitem'),
        ),
    ]
