# Generated by Django 6.0.6 on 2026-07-06 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_surgery_consumable_inventory_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_invoice_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='credit_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='credit_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_approved_invoice_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='credit_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='payment_status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Credit Approved', 'Credit Approved'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending Payment', max_length=20),
        ),
        migrations.AddField(
            model_name='surgeryconsumable',
            name='invoice_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_consumable', to='core.invoiceitem'),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='invoice_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_order', to='core.invoiceitem'),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='payment_status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Paid', 'Paid'), ('Partial', 'Partially Paid'), ('Credit', 'Credit'), ('Waived', 'Waived')], default='Pending Payment', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceItemRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('refunded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_refunds', to='core.invoiceitem')),
                ('refunded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Item Refund',
                'ordering': ['-refunded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='core.invoiceitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.payment')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'ordering': ['invoice_item_id'],
            },
        ),
    ]
