# Generated by Django 6.0.6 on 2026-07-06 10:16

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_item_level_payment_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriopNursingAddendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('anesthesia', 'Pre-Op Anesthetic Assessment'), ('operative', 'OR Operative Note'), ('postop', 'Post-Operative Note')], max_length=15)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perioperative Nursing Addendum',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostOperativeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('doc_status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=10)),
                ('revision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('signature_name', models.CharField(blank=True, max_length=200)),
                ('consciousness_level', models.CharField(blank=True, choices=[('alert', 'Alert'), ('drowsy', 'Drowsy'), ('sedated', 'Sedated'), ('unresponsive', 'Unresponsive')], max_length=15)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('po_bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('po_bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('po_pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('po_respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('po_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('po_spo2', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('airway_status', models.CharField(blank=True, max_length=150)),
                ('o2_requirement', models.CharField(blank=True, max_length=150)),
                ('neuro_status', models.TextField(blank=True)),
                ('wound_condition', models.TextField(blank=True)),
                ('drain_status', models.TextField(blank=True)),
                ('catheters_present', models.TextField(blank=True)),
                ('bleeding_assessment', models.TextField(blank=True)),
                ('post_op_complications', models.TextField(blank=True)),
                ('immediate_post_op_diagnosis', models.TextField(blank=True)),
                ('diet_orders', models.CharField(blank=True, max_length=200)),
                ('iv_fluids_orders', models.TextField(blank=True)),
                ('medication_orders', models.TextField(blank=True)),
                ('antibiotic_orders', models.TextField(blank=True)),
                ('pain_management_plan', models.TextField(blank=True)),
                ('dvt_prophylaxis', models.TextField(blank=True)),
                ('physiotherapy_orders', models.TextField(blank=True)),
                ('nursing_instructions', models.TextField(blank=True)),
                ('activity_level', models.CharField(blank=True, max_length=200)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('lab_orders', models.TextField(blank=True)),
                ('imaging_orders', models.TextField(blank=True)),
                ('disposition', models.CharField(blank=True, choices=[('pacu', 'Recovery Room (PACU)'), ('icu', 'ICU'), ('ward', 'Ward'), ('hdu', 'HDU'), ('discharge', 'Discharge')], max_length=15)),
                ('disposition_notes', models.TextField(blank=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('dressing_change_plan', models.CharField(blank=True, max_length=200)),
                ('drain_removal_plan', models.CharField(blank=True, max_length=200)),
                ('suture_removal_plan', models.CharField(blank=True, max_length=200)),
                ('additional_procedures_planned', models.TextField(blank=True)),
                ('outpatient_followup_instructions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Post-Operative Note',
                'ordering': ['-version'],
            },
        ),
        migrations.AlterModelOptions(
            name='hmspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_queue', 'Can manage patient queue'), ('perform_triage', 'Can perform triage assessment'), ('write_clinical_note', 'Can write clinical notes'), ('read_clinical_note', 'Can read clinical notes'), ('write_nursing_note', 'Can write nursing notes'), ('read_nursing_note', 'Can read nursing notes'), ('record_vital_signs', 'Can record vital signs'), ('read_vital_signs', 'Can read vital signs'), ('write_care_plan', 'Can write care plans'), ('read_care_plan', 'Can read care plans'), ('write_diagnosis', 'Can write diagnosis'), ('read_diagnosis', 'Can read diagnosis records'), ('write_prescription', 'Can write prescriptions'), ('read_prescription', 'Can read prescriptions'), ('request_lab_test', 'Can request laboratory tests'), ('read_lab_request', 'Can read lab requests'), ('process_lab_test', 'Can process lab tests / enter results'), ('write_lab_result', 'Can write lab results'), ('read_lab_result', 'Can read lab results'), ('collect_lab_sample', 'Can record sample collection'), ('release_lab_result', 'Can release lab results to patient'), ('manage_lab_services', 'Can manage lab service catalogue and pricing'), ('view_lab_reports', 'Can view laboratory management reports'), ('request_imaging', 'Can request imaging studies'), ('read_imaging_request', 'Can read imaging requests'), ('process_imaging', 'Can process imaging studies'), ('write_imaging_report', 'Can write imaging reports'), ('read_imaging_report', 'Can read imaging reports'), ('manage_imaging_services', 'Can manage imaging service catalogue and pricing'), ('write_anesthesia_record', 'Can write anesthesia records'), ('read_anesthesia_record', 'Can read anesthesia records'), ('read_billing', 'Can read billing records'), ('create_invoice', 'Can create invoices'), ('manage_billing', 'Can manage all billing records'), ('process_payment', 'Can process payments'), ('approve_credit_invoice', 'Can approve credit invoices'), ('manage_cash_sessions', 'Can open and close cash sessions'), ('read_financial_report', 'Can read financial reports'), ('read_medication_inventory', 'Can read medication inventory'), ('manage_medication', 'Can manage medication inventory'), ('dispense_medication', 'Can dispense medications'), ('read_prescription_for_dispensing', 'Can read prescriptions for dispensing'), ('process_pharmacy_sale', 'Can process pharmacy sales'), ('approve_pharmacy_discount', 'Can approve pharmacy discounts'), ('approve_credit_sale', 'Can approve credit pharmacy sales'), ('manage_pharmacy_returns', 'Can process pharmacy returns/refunds'), ('read_pharmacy_reports', 'Can view pharmacy sales reports'), ('view_dept_inventory', 'Can view department store inventory'), ('manage_dept_stores', 'Can create and edit department stores'), ('request_medication_transfer', 'Can request medication transfers'), ('approve_medication_transfer', 'Can approve / fulfill medication transfers'), ('record_dept_usage', 'Can record medication usage in department'), ('view_dept_reports', 'Can view department pharmacy reports'), ('manage_med_catalog', 'Can manage medication catalog'), ('receive_stock', 'Can receive stock / create batches'), ('manage_suppliers', 'Can manage suppliers'), ('view_inv_reports', 'Can view inventory reports'), ('export_inv_reports', 'Can export inventory reports'), ('read_inventory', 'Can read store inventory'), ('manage_inventory', 'Can manage store inventory'), ('create_purchase_order', 'Can create purchase orders'), ('approve_purchase_order', 'Can approve purchase orders'), ('create_purchase_request', 'Can create purchase requests'), ('approve_purchase_request', 'Can approve purchase requests'), ('issue_inventory', 'Can issue items from store'), ('manage_inventory_batches', 'Can receive and manage inventory batches'), ('manage_equipment_assets', 'Can manage equipment and asset records'), ('perform_stock_count', 'Can perform physical stock count'), ('approve_stock_count', 'Can approve stock count results'), ('view_store_reports', 'Can view store reports'), ('export_store_reports', 'Can export store reports'), ('read_employee', 'Can read employee records'), ('manage_employees', 'Can manage employee records'), ('manage_attendance', 'Can manage attendance'), ('manage_payroll', 'Can manage payroll'), ('read_appointment', 'Can read appointments'), ('manage_appointments', 'Can manage appointments'), ('manage_doctor_availability', 'Can manage doctor schedules and availability'), ('view_appointment_reports', 'Can view appointment reports'), ('export_appointment_reports', 'Can export appointment reports'), ('read_clinical_reports', 'Can read clinical reports'), ('read_department_reports', 'Can read department reports'), ('manage_users', 'Can manage system users'), ('manage_roles', 'Can manage roles and permissions'), ('system_configuration', 'Can access system configuration'), ('read_audit_log', 'Can read audit logs'), ('manage_departments', 'Can manage departments'), ('view_patient_flow', 'Can view the patient flow dashboard'), ('manage_patient_flow', 'Can update patient journey status'), ('manage_discharge', 'Can create and manage discharge summaries'), ('view_dept_worklist', 'Can view department work list'), ('manage_procedure_master', 'Can manage procedure/surgery master list'), ('order_surgery', 'Can create and manage surgery orders'), ('approve_surgery_order', 'Can approve or reject surgery orders'), ('manage_or_schedule', 'Can manage OR schedule and room assignments'), ('write_surgery_anesthesia', 'Can write surgery anesthesia records'), ('read_surgery', 'Can read surgery orders and records'), ('write_operative_note', 'Can write operative notes'), ('manage_surgery_consumables', 'Can manage surgery consumables and supplies'), ('generate_surgery_billing', 'Can generate billing from surgery orders'), ('read_surgery_reports', 'Can read surgery reports'), ('write_postop_note', 'Can write post-operative notes'), ('read_postop_note', 'Can read post-operative notes'), ('add_periop_nursing_note', 'Can add nursing addenda to perioperative documents'), ('read_periop_document_history', 'Can view perioperative document version history')], 'verbose_name': 'HMS Permission', 'verbose_name_plural': 'HMS Permissions'},
        ),
        migrations.AlterModelOptions(
            name='operativenote',
            options={'ordering': ['-version'], 'verbose_name': 'Operative Note'},
        ),
        migrations.AlterModelOptions(
            name='surgeryanesthesiarecord',
            options={'ordering': ['-version'], 'verbose_name': 'Surgery Anesthesia Record'},
        ),
        migrations.RemoveField(
            model_name='operativenote',
            name='authored_at',
        ),
        migrations.RemoveField(
            model_name='operativenote',
            name='authored_by',
        ),
        migrations.RemoveField(
            model_name='operativenote',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='operativenote',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='surgeryanesthesiarecord',
            name='anesthesiologist',
        ),
        migrations.AddField(
            model_name='operativenote',
            name='blood_transfusion_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='blood_transfusion_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='counts_correct',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'Not Applicable')], max_length=5),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 6, 10, 16, 16, 214243, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operativenote',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operativenote',
            name='doc_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='dressings_applied',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_finalized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='incision_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='intraop_events',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='revision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='signature_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_superseded_by', to='core.operativenote'),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='surgical_technique',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='time_patient_entered_or',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='time_patient_left_or',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='time_surgery_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='time_surgery_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='unexpected_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='wound_classification',
            field=models.CharField(blank=True, choices=[('clean', 'Clean'), ('clean_contaminated', 'Clean-Contaminated'), ('contaminated', 'Contaminated'), ('dirty_infected', 'Dirty-Infected')], max_length=20),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='alcohol_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='alcohol_use',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('occasional', 'Occasional'), ('regular', 'Regular'), ('heavy', 'Heavy'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='anesthesia_type_planned',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='assessment_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='blood_products_required',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='chronic_diseases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='cvs_exam',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='dentition_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='difficult_airway_anticipated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='difficult_airway_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='doc_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='final_assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_finalized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='fitness_for_surgery',
            field=models.CharField(blank=True, choices=[('fit', 'Fit for Surgery'), ('fit_precautions', 'Fit with Precautions'), ('not_fit', 'Not Fit'), ('deferred', 'Deferred')], max_length=20),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='general_appearance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='lab_review_blood_group',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='lab_review_blood_sugar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='lab_review_cbc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='lab_review_coagulation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='lab_review_cxr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='lab_review_ecg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='lab_review_lft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='lab_review_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='lab_review_rft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='mallampati_class',
            field=models.CharField(blank=True, choices=[('I', 'Class I'), ('II', 'Class II'), ('III', 'Class III'), ('IV', 'Class IV')], max_length=5),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='monitoring_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='mouth_opening',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='neck_mobility',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('reduced', 'Reduced'), ('severe', 'Severely Reduced')], max_length=10),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='neuro_exam',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='npo_fasting_status',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='past_medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='pe_bp_diastolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='pe_bp_systolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='pe_height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='pe_pulse',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='pe_respiratory_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='pe_spo2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='pe_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='pe_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='pregnancy_status',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('not_pregnant', 'Not Pregnant'), ('pregnant', 'Pregnant'), ('unknown', 'Unknown')], max_length=15),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='present_illness_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='previous_anesthesia_complications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='previous_anesthesia_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='previous_surgeries_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='respiratory_exam',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='revision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='risk_assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='signature_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='smoking_pack_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('former', 'Former'), ('current', 'Current'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='special_equipment_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_superseded_by', to='core.surgeryanesthesiarecord'),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='thyromental_distance_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgeryanesthesiarecord',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='operativenote',
            name='assistant_surgeons',
        ),
        migrations.AlterField(
            model_name='operativenote',
            name='surgery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operative_notes', to='core.surgeryorder'),
        ),
        migrations.AlterField(
            model_name='surgeryanesthesiarecord',
            name='surgery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anesthesia_records', to='core.surgeryorder'),
        ),
        migrations.AddConstraint(
            model_name='operativenote',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('surgery_order',), name='unique_current_operative_note_per_order'),
        ),
        migrations.AddConstraint(
            model_name='surgeryanesthesiarecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('surgery_order',), name='unique_current_anesthesia_record_per_order'),
        ),
        migrations.AddField(
            model_name='periopnursingaddendum',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periop_nursing_addenda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periopnursingaddendum',
            name='surgery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_addenda', to='core.surgeryorder'),
        ),
        migrations.AddField(
            model_name='postoperativenote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postoperativenote',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_finalized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postoperativenote',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_superseded_by', to='core.postoperativenote'),
        ),
        migrations.AddField(
            model_name='postoperativenote',
            name='surgery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postop_notes', to='core.surgeryorder'),
        ),
        migrations.AddField(
            model_name='postoperativenote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operativenote',
            name='assistant_surgeons',
            field=models.ManyToManyField(blank=True, related_name='operative_notes_assisted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='postoperativenote',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('surgery_order',), name='unique_current_postop_note_per_order'),
        ),
    ]
