# Generated by Django 6.0.6 on 2026-07-06 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_perioperative_documentation_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Building',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_name', models.CharField(blank=True, max_length=100)),
                ('room_type', models.CharField(choices=[('standard', 'Standard Room'), ('private', 'Private Room'), ('vip', 'VIP Room'), ('isolation', 'Isolation Room'), ('icu', 'ICU Room'), ('recovery', 'Recovery Room')], default='standard', max_length=15)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('privacy_type', models.CharField(choices=[('private', 'Private'), ('semi_private', 'Semi-private'), ('common', 'Common')], default='semi_private', max_length=15)),
                ('is_ac', models.BooleanField(default=False)),
                ('is_isolation', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('maintenance', 'Under Maintenance')], default='active', max_length=15)),
            ],
            options={
                'verbose_name': 'Room',
                'ordering': ['ward__name', 'room_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='hmspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_queue', 'Can manage patient queue'), ('perform_triage', 'Can perform triage assessment'), ('write_clinical_note', 'Can write clinical notes'), ('read_clinical_note', 'Can read clinical notes'), ('write_nursing_note', 'Can write nursing notes'), ('read_nursing_note', 'Can read nursing notes'), ('record_vital_signs', 'Can record vital signs'), ('read_vital_signs', 'Can read vital signs'), ('write_care_plan', 'Can write care plans'), ('read_care_plan', 'Can read care plans'), ('write_diagnosis', 'Can write diagnosis'), ('read_diagnosis', 'Can read diagnosis records'), ('write_prescription', 'Can write prescriptions'), ('read_prescription', 'Can read prescriptions'), ('request_lab_test', 'Can request laboratory tests'), ('read_lab_request', 'Can read lab requests'), ('process_lab_test', 'Can process lab tests / enter results'), ('write_lab_result', 'Can write lab results'), ('read_lab_result', 'Can read lab results'), ('collect_lab_sample', 'Can record sample collection'), ('release_lab_result', 'Can release lab results to patient'), ('manage_lab_services', 'Can manage lab service catalogue and pricing'), ('view_lab_reports', 'Can view laboratory management reports'), ('request_imaging', 'Can request imaging studies'), ('read_imaging_request', 'Can read imaging requests'), ('process_imaging', 'Can process imaging studies'), ('write_imaging_report', 'Can write imaging reports'), ('read_imaging_report', 'Can read imaging reports'), ('manage_imaging_services', 'Can manage imaging service catalogue and pricing'), ('write_anesthesia_record', 'Can write anesthesia records'), ('read_anesthesia_record', 'Can read anesthesia records'), ('read_billing', 'Can read billing records'), ('create_invoice', 'Can create invoices'), ('manage_billing', 'Can manage all billing records'), ('process_payment', 'Can process payments'), ('approve_credit_invoice', 'Can approve credit invoices'), ('manage_cash_sessions', 'Can open and close cash sessions'), ('read_financial_report', 'Can read financial reports'), ('read_medication_inventory', 'Can read medication inventory'), ('manage_medication', 'Can manage medication inventory'), ('dispense_medication', 'Can dispense medications'), ('read_prescription_for_dispensing', 'Can read prescriptions for dispensing'), ('process_pharmacy_sale', 'Can process pharmacy sales'), ('approve_pharmacy_discount', 'Can approve pharmacy discounts'), ('approve_credit_sale', 'Can approve credit pharmacy sales'), ('manage_pharmacy_returns', 'Can process pharmacy returns/refunds'), ('read_pharmacy_reports', 'Can view pharmacy sales reports'), ('view_dept_inventory', 'Can view department store inventory'), ('manage_dept_stores', 'Can create and edit department stores'), ('request_medication_transfer', 'Can request medication transfers'), ('approve_medication_transfer', 'Can approve / fulfill medication transfers'), ('record_dept_usage', 'Can record medication usage in department'), ('view_dept_reports', 'Can view department pharmacy reports'), ('manage_med_catalog', 'Can manage medication catalog'), ('receive_stock', 'Can receive stock / create batches'), ('manage_suppliers', 'Can manage suppliers'), ('view_inv_reports', 'Can view inventory reports'), ('export_inv_reports', 'Can export inventory reports'), ('read_inventory', 'Can read store inventory'), ('manage_inventory', 'Can manage store inventory'), ('create_purchase_order', 'Can create purchase orders'), ('approve_purchase_order', 'Can approve purchase orders'), ('create_purchase_request', 'Can create purchase requests'), ('approve_purchase_request', 'Can approve purchase requests'), ('issue_inventory', 'Can issue items from store'), ('manage_inventory_batches', 'Can receive and manage inventory batches'), ('manage_equipment_assets', 'Can manage equipment and asset records'), ('perform_stock_count', 'Can perform physical stock count'), ('approve_stock_count', 'Can approve stock count results'), ('view_store_reports', 'Can view store reports'), ('export_store_reports', 'Can export store reports'), ('read_employee', 'Can read employee records'), ('manage_employees', 'Can manage employee records'), ('manage_attendance', 'Can manage attendance'), ('manage_payroll', 'Can manage payroll'), ('read_appointment', 'Can read appointments'), ('manage_appointments', 'Can manage appointments'), ('manage_doctor_availability', 'Can manage doctor schedules and availability'), ('view_appointment_reports', 'Can view appointment reports'), ('export_appointment_reports', 'Can export appointment reports'), ('read_clinical_reports', 'Can read clinical reports'), ('read_department_reports', 'Can read department reports'), ('manage_users', 'Can manage system users'), ('manage_roles', 'Can manage roles and permissions'), ('system_configuration', 'Can access system configuration'), ('read_audit_log', 'Can read audit logs'), ('manage_departments', 'Can manage departments'), ('view_patient_flow', 'Can view the patient flow dashboard'), ('manage_patient_flow', 'Can update patient journey status'), ('manage_discharge', 'Can create and manage discharge summaries'), ('view_dept_worklist', 'Can view department work list'), ('manage_procedure_master', 'Can manage procedure/surgery master list'), ('order_surgery', 'Can create and manage surgery orders'), ('approve_surgery_order', 'Can approve or reject surgery orders'), ('manage_or_schedule', 'Can manage OR schedule and room assignments'), ('write_surgery_anesthesia', 'Can write surgery anesthesia records'), ('read_surgery', 'Can read surgery orders and records'), ('write_operative_note', 'Can write operative notes'), ('manage_surgery_consumables', 'Can manage surgery consumables and supplies'), ('generate_surgery_billing', 'Can generate billing from surgery orders'), ('read_surgery_reports', 'Can read surgery reports'), ('write_postop_note', 'Can write post-operative notes'), ('read_postop_note', 'Can read post-operative notes'), ('add_periop_nursing_note', 'Can add nursing addenda to perioperative documents'), ('read_periop_document_history', 'Can view perioperative document version history'), ('manage_facilities', 'Can add, edit, and delete buildings, wards, rooms, beds, and OR configuration'), ('view_facility', 'Can view facility lists and dashboard'), ('assign_bed', 'Can admit, transfer, and discharge patients to/from beds'), ('view_facility_reports', 'Can view facility management reports')], 'verbose_name': 'HMS Permission', 'verbose_name_plural': 'HMS Permissions'},
        ),
        migrations.AddField(
            model_name='orroom',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='available', max_length=15),
        ),
        migrations.AddField(
            model_name='orroom',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orroom',
            name='daily_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orroom',
            name='daily_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orroom',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='or_rooms', to='core.department'),
        ),
        migrations.AddField(
            model_name='orroom',
            name='max_surgeries_per_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('patient', 'Patient'), ('appointment', 'Appointment'), ('visit', 'Visit'), ('doctor', 'Doctor / Clinical'), ('nursing', 'Nursing'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('med_inventory', 'Medication Inventory'), ('dept_pharmacy', 'Dept Pharmacy'), ('inventory', 'Store & Inventory'), ('billing', 'Billing'), ('payment', 'Payment'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('admin', 'Administration'), ('auth', 'Authentication'), ('user', 'User Management'), ('anesthesia', 'Anesthesia'), ('queue', 'Queue / Triage'), ('surgery', 'Surgery'), ('facility', 'Facility Management')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_type',
            field=models.CharField(choices=[('administration', 'Administration'), ('clinical', 'Medical / Clinical'), ('nursing', 'Nursing'), ('emergency', 'Emergency'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('or', 'Operating Room'), ('ward', 'Ward / Inpatient'), ('icu', 'Intensive Care Unit'), ('opd', 'Outpatient'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('store', 'Store / Inventory'), ('maternity', 'Maternity / Labour'), ('pediatrics', 'Pediatrics'), ('other', 'Other'), ('day_surgery', 'Day Surgery Unit'), ('blood_bank', 'Blood Bank'), ('physiotherapy', 'Physiotherapy'), ('dental', 'Dental Clinic'), ('eye_clinic', 'Eye Clinic'), ('ent_clinic', 'ENT Clinic'), ('dermatology', 'Dermatology Clinic'), ('vaccination', 'Vaccination Clinic'), ('cssd', 'Central Sterile Supply Department'), ('medical_records', 'Medical Records')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='orroom',
            name='room_type',
            field=models.CharField(choices=[('general', 'General Surgery'), ('cardiac', 'Cardiac / Thoracic'), ('orthopedic', 'Orthopedic'), ('neuro', 'Neurosurgery'), ('eye', 'Ophthalmic'), ('gynecology', 'Gynecology'), ('ent', 'ENT'), ('emergency', 'Emergency OR'), ('procedure', 'Procedure Room'), ('other', 'Other')], default='general', max_length=15),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('bed_code', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=15)),
                ('current_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_beds', to='core.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='core.room')),
            ],
            options={
                'verbose_name': 'Bed',
                'ordering': ['room__ward__name', 'room__room_number', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred')], default='admitted', max_length=15)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_reason', models.TextField(blank=True)),
                ('admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_performed', to=settings.AUTH_USER_MODEL)),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges_performed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='core.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.visit')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='core.bed')),
            ],
            options={
                'verbose_name': 'Admission',
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='core.building'),
        ),
        migrations.AddField(
            model_name='orroom',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='or_rooms', to='core.building'),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level_order', models.SmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='core.building')),
            ],
            options={
                'verbose_name': 'Floor',
                'ordering': ['building__name', 'level_order'],
                'unique_together': {('building', 'name')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='core.floor'),
        ),
        migrations.AddField(
            model_name='orroom',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='or_rooms', to='core.floor'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('ward_type', models.CharField(choices=[('medical', 'Medical Ward'), ('surgical', 'Surgical Ward'), ('pediatric', 'Pediatric Ward'), ('maternity', 'Maternity Ward'), ('icu', 'ICU'), ('nicu', 'NICU'), ('picu', 'PICU'), ('hdu', 'HDU'), ('isolation', 'Isolation Ward'), ('other', 'Other')], default='medical', max_length=15)),
                ('gender_restriction', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('is_isolation', models.BooleanField(default=False)),
                ('is_icu_hdu', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='core.building')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='core.department')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='core.floor')),
            ],
            options={
                'verbose_name': 'Ward',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.ward'),
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='core.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('ward', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
    ]
