# Generated by Django 6.0.6 on 2026-07-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_facility_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('New Consultation', 'New Consultation'), ('Follow-up', 'Follow-up'), ('Emergency', 'Emergency'), ('Procedure', 'Procedure'), ('Review', 'Review'), ('Follow-up Consultation', 'Follow-up Consultation'), ('Post-Procedure Review', 'Post-Procedure Review'), ('Post-Operative Follow-up', 'Post-Operative Follow-up'), ('Wound Dressing', 'Wound Dressing'), ('Suture Removal', 'Suture Removal'), ('Laboratory Result Review', 'Laboratory Result Review'), ('Imaging Result Review', 'Imaging Result Review'), ('Chronic Disease Follow-up', 'Chronic Disease Follow-up'), ('Medication Review', 'Medication Review'), ('Other', 'Other (Custom)')], default='New Consultation', max_length=30),
        ),
    ]
