# Generated by Django 6.0.6 on 2026-07-08 17:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_walkin_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='service_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Laboratory', 'Laboratory'), ('Imaging', 'Imaging'), ('Medication', 'Medication'), ('Procedure', 'Procedure'), ('Bed / Room', 'Bed / Room'), ('Nursing Care', 'Nursing Care'), ('Service Charge', 'Service Charge'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceChargeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5)),
                ('charge_name', models.CharField(default='Service Charge', max_length=100)),
                ('allow_cashier_override', models.BooleanField(default=True)),
                ('default_disabled_service_types', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_charge_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Charge Settings',
                'verbose_name_plural': 'Service Charge Settings',
            },
        ),
    ]
