# Generated by Django 6.0.6 on 2026-07-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_card_consultation_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Used automatically at appointment check-in, where the receptionist does not pick a card type by hand.'),
        ),
        migrations.AddField(
            model_name='consultationtype',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Used automatically at appointment check-in for this department (or hospital-wide) when the receptionist does not pick one by hand.'),
        ),
    ]
