# Generated by Django 6.0.6 on 2026-07-09 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_doctor_specialization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hmspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_queue', 'Can manage patient queue'), ('perform_triage', 'Can perform triage assessment'), ('write_clinical_note', 'Can write clinical notes'), ('read_clinical_note', 'Can read clinical notes'), ('write_nursing_note', 'Can write nursing notes'), ('read_nursing_note', 'Can read nursing notes'), ('record_vital_signs', 'Can record vital signs'), ('read_vital_signs', 'Can read vital signs'), ('write_care_plan', 'Can write care plans'), ('read_care_plan', 'Can read care plans'), ('write_diagnosis', 'Can write diagnosis'), ('read_diagnosis', 'Can read diagnosis records'), ('write_prescription', 'Can write prescriptions'), ('read_prescription', 'Can read prescriptions'), ('request_lab_test', 'Can request laboratory tests'), ('read_lab_request', 'Can read lab requests'), ('process_lab_test', 'Can process lab tests / enter results'), ('write_lab_result', 'Can write lab results'), ('read_lab_result', 'Can read lab results'), ('collect_lab_sample', 'Can record sample collection'), ('release_lab_result', 'Can release lab results to patient'), ('manage_lab_services', 'Can manage lab service catalogue and pricing'), ('view_lab_reports', 'Can view laboratory management reports'), ('request_imaging', 'Can request imaging studies'), ('read_imaging_request', 'Can read imaging requests'), ('process_imaging', 'Can process imaging studies'), ('write_imaging_report', 'Can write imaging reports'), ('read_imaging_report', 'Can read imaging reports'), ('manage_imaging_services', 'Can manage imaging service catalogue and pricing'), ('write_anesthesia_record', 'Can write anesthesia records'), ('read_anesthesia_record', 'Can read anesthesia records'), ('read_billing', 'Can read billing records'), ('create_invoice', 'Can create invoices'), ('manage_billing', 'Can manage all billing records'), ('process_payment', 'Can process payments'), ('approve_credit_invoice', 'Can approve credit invoices'), ('manage_cash_sessions', 'Can open and close cash sessions'), ('read_financial_report', 'Can read financial reports'), ('read_medication_inventory', 'Can read medication inventory'), ('manage_medication', 'Can manage medication inventory'), ('dispense_medication', 'Can dispense medications'), ('read_prescription_for_dispensing', 'Can read prescriptions for dispensing'), ('process_pharmacy_sale', 'Can process pharmacy sales'), ('approve_pharmacy_discount', 'Can approve pharmacy discounts'), ('approve_credit_sale', 'Can approve credit pharmacy sales'), ('manage_pharmacy_returns', 'Can process pharmacy returns/refunds'), ('read_pharmacy_reports', 'Can view pharmacy sales reports'), ('view_dept_inventory', 'Can view department store inventory'), ('manage_dept_stores', 'Can create and edit department stores'), ('request_medication_transfer', 'Can request medication transfers'), ('approve_medication_transfer', 'Can approve / fulfill medication transfers'), ('record_dept_usage', 'Can record medication usage in department'), ('view_dept_reports', 'Can view department pharmacy reports'), ('manage_med_catalog', 'Can manage medication catalog'), ('receive_stock', 'Can receive stock / create batches'), ('manage_suppliers', 'Can manage suppliers'), ('view_inv_reports', 'Can view inventory reports'), ('export_inv_reports', 'Can export inventory reports'), ('read_inventory', 'Can read store inventory'), ('manage_inventory', 'Can manage store inventory'), ('create_purchase_order', 'Can create purchase orders'), ('approve_purchase_order', 'Can approve purchase orders'), ('create_purchase_request', 'Can create purchase requests'), ('approve_purchase_request', 'Can approve purchase requests'), ('issue_inventory', 'Can issue items from store'), ('manage_inventory_batches', 'Can receive and manage inventory batches'), ('manage_equipment_assets', 'Can manage equipment and asset records'), ('perform_stock_count', 'Can perform physical stock count'), ('approve_stock_count', 'Can approve stock count results'), ('view_store_reports', 'Can view store reports'), ('export_store_reports', 'Can export store reports'), ('manage_inventory_periods', 'Can open and close inventory periods (annual/quarterly/monthly)'), ('read_employee', 'Can read employee records'), ('manage_employees', 'Can manage employee records'), ('manage_attendance', 'Can manage attendance'), ('manage_payroll', 'Can manage payroll'), ('read_appointment', 'Can read appointments'), ('manage_appointments', 'Can manage appointments'), ('manage_doctor_availability', 'Can manage doctor schedules and availability'), ('view_appointment_reports', 'Can view appointment reports'), ('export_appointment_reports', 'Can export appointment reports'), ('read_clinical_reports', 'Can read clinical reports'), ('read_department_reports', 'Can read department reports'), ('manage_users', 'Can manage system users'), ('manage_roles', 'Can manage roles and permissions'), ('system_configuration', 'Can access system configuration'), ('read_audit_log', 'Can read audit logs'), ('manage_departments', 'Can manage departments'), ('view_patient_flow', 'Can view the patient flow dashboard'), ('manage_patient_flow', 'Can update patient journey status'), ('manage_discharge', 'Can create and manage discharge summaries'), ('view_dept_worklist', 'Can view department work list'), ('manage_procedure_master', 'Can manage procedure/surgery master list'), ('order_surgery', 'Can create and manage surgery orders'), ('approve_surgery_order', 'Can approve or reject surgery orders'), ('manage_or_schedule', 'Can manage OR schedule and room assignments'), ('write_surgery_anesthesia', 'Can write surgery anesthesia records'), ('read_surgery', 'Can read surgery orders and records'), ('write_operative_note', 'Can write operative notes'), ('manage_surgery_consumables', 'Can manage surgery consumables and supplies'), ('generate_surgery_billing', 'Can generate billing from surgery orders'), ('read_surgery_reports', 'Can read surgery reports'), ('write_postop_note', 'Can write post-operative notes'), ('read_postop_note', 'Can read post-operative notes'), ('add_periop_nursing_note', 'Can add nursing addenda to perioperative documents'), ('read_periop_document_history', 'Can view perioperative document version history'), ('manage_facilities', 'Can add, edit, and delete buildings, wards, rooms, beds, and OR configuration'), ('view_facility', 'Can view facility lists and dashboard'), ('assign_bed', 'Can admit, transfer, and discharge patients to/from beds'), ('view_facility_reports', 'Can view facility management reports'), ('manage_card_types', 'Can create, edit, and deactivate card types and consultation types'), ('override_card_expiry', 'Can waive the card renewal fee for an expired/missing card'), ('view_card_reports', 'Can view card and consultation type reports'), ('manage_specializations', 'Can create, edit, and deactivate medical specializations'), ('manage_doctors', 'Can create and edit doctor staff records'), ('view_specialization_reports', 'Can view specialization reports')], 'verbose_name': 'HMS Permission', 'verbose_name_plural': 'HMS Permissions'},
        ),
        migrations.CreateModel(
            name='InventoryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "2026 Inventory Period"', max_length=100, unique=True)),
                ('period_type', models.CharField(choices=[('Annual', 'Annual'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly')], default='Annual', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_periods_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_periods_opened', to=settings.AUTH_USER_MODEL)),
                ('previous_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_periods', to='core.inventoryperiod')),
            ],
            options={
                'verbose_name': 'Inventory Period',
                'verbose_name_plural': 'Inventory Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('count_type', models.CharField(choices=[('Annual', 'Annual Inventory Count'), ('Quarterly', 'Quarterly Inventory Count'), ('Monthly', 'Monthly Inventory Count'), ('Cycle', 'Cycle Count (Selected Items)'), ('Emergency', 'Emergency Stock Verification')], default='Annual', max_length=10)),
                ('domain', models.CharField(choices=[('general_store', 'Main / General Store'), ('medication', 'Pharmacy (Medication Inventory)'), ('department_store', 'Department Store (Ward / OR / ER / ICU ...)')], default='general_store', max_length=20)),
                ('freeze_snapshot', models.BooleanField(default=True, help_text='Freeze system quantities at the moment the count starts, so later transactions during counting do not change what staff are reconciling against.')),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted for Approval'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Planned', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_counts_approved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Optional — narrows a General Store count to one category (cycle count).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_counts', to='core.inventorycategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_counts_created', to=settings.AUTH_USER_MODEL)),
                ('department_store', models.ForeignKey(blank=True, help_text='Required when domain = Department Store.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_counts', to='core.departmentstore')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_counts', to='core.inventoryperiod')),
            ],
            options={
                'verbose_name': 'Physical Inventory Count',
                'verbose_name_plural': 'Physical Inventory Counts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('system_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('physical_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('is_approved', models.BooleanField(default=False)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_count_lines_counted', to=settings.AUTH_USER_MODEL)),
                ('department_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_count_lines', to='core.departmentstock')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_count_lines', to='core.inventoryitem')),
                ('medication_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_count_lines', to='core.medicationbatch')),
                ('physical_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.physicalcount')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_count_lines_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Physical Count Line',
                'verbose_name_plural': 'Physical Count Lines',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('general_store', 'Main / General Store'), ('medication', 'Pharmacy (Medication Inventory)'), ('department_store', 'Department Store (Ward / OR / ER / ICU ...)')], max_length=20)),
                ('item_description', models.CharField(max_length=255)),
                ('previous_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('physical_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=4, max_digits=14)),
                ('adjustment_type', models.CharField(choices=[('Increase', 'Increase'), ('Decrease', 'Decrease')], max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments_approved', to=settings.AUTH_USER_MODEL)),
                ('physical_count_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='core.physicalcountline')),
            ],
            options={
                'verbose_name': 'Inventory Adjustment',
                'verbose_name_plural': 'Inventory Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPeriodBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.CharField(choices=[('Opening', 'Opening Balance'), ('Closing', 'Closing Balance')], max_length=10)),
                ('domain', models.CharField(choices=[('general_store', 'Main / General Store'), ('medication', 'Pharmacy (Medication Inventory)'), ('department_store', 'Department Store (Ward / OR / ER / ICU ...)')], max_length=20)),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valuation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carried_from_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_to', to='core.inventoryperiodbalance')),
                ('department_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_balances', to='core.departmentstock')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_balances', to='core.inventoryitem')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_balances', to='core.medication')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='core.inventoryperiod')),
            ],
            options={
                'verbose_name': 'Inventory Period Balance',
                'verbose_name_plural': 'Inventory Period Balances',
                'ordering': ['domain', 'item_name'],
                'indexes': [models.Index(fields=['period', 'balance_type', 'domain'], name='core_invent_period__e56acd_idx')],
            },
        ),
    ]
