# Generated by Django 6.0.6 on 2026-07-09 12:10, hand-edited to safely
# migrate LabService.section (hardcoded TextChoices) -> LabService.category
# (admin-managed LabCategory FK) without a risky in-place column-type ALTER:
# 1. add the new nullable `category` FK as its own column (old `category`
#    CharField is dropped first, freeing the name)
# 2. RunPython backfill: for every existing LabService row, resolve/create a
#    LabCategory matching its old `section` value and point `category` at it
# 3. only then drop `section`
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SECTION_TO_CATEGORY_NAME = {
    'Hematology':   'Hematology',
    'Chemistry':    'Clinical Chemistry',
    'Microbiology': 'Microbiology',
    'Immunology':   'Immunology',
    'Pathology':    'Histopathology',
    'Parasitology': 'Parasitology',
    'Serology':     'Serology',
    'Genetics':     'Molecular Diagnostics',
    'Other':        'Other',
}


def backfill_category_from_section(apps, schema_editor):
    LabService = apps.get_model('core', 'LabService')
    LabCategory = apps.get_model('core', 'LabCategory')
    db_alias = schema_editor.connection.alias

    category_cache = {}
    for svc in LabService.objects.using(db_alias).all():
        category_name = SECTION_TO_CATEGORY_NAME.get(svc.section, 'Other')
        if category_name not in category_cache:
            category, _ = LabCategory.objects.using(db_alias).get_or_create(
                name=category_name, defaults={'display_order': 0, 'is_active': True},
            )
            category_cache[category_name] = category
        svc.category_id = category_cache[category_name].id
        svc.save(using=db_alias, update_fields=['category'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_employee_signature_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lab Category',
                'verbose_name_plural': 'Lab Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lab Test Group',
                'verbose_name_plural': 'Lab Test Groups',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestResultOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lab Test Result Option',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='labservice',
            options={'ordering': ['category__display_order', 'display_order', 'name'], 'verbose_name': 'Lab Service', 'verbose_name_plural': 'Lab Services'},
        ),
        migrations.RemoveIndex(
            model_name='labservice',
            name='core_labser_is_acti_60b787_idx',
        ),
        migrations.AddField(
            model_name='laborder',
            name='critical_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='critical_flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_flagged_critical', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborder',
            name='critical_notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='laborder',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labservice',
            name='critical_values',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='labservice',
            name='default_result',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='labservice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_services', to='core.department'),
        ),
        migrations.AddField(
            model_name='labservice',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labservice',
            name='is_printable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labservice',
            name='linked_inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_services', to='core.inventoryitem'),
        ),
        migrations.AddField(
            model_name='labservice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labservice',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_tests', to='core.labservice'),
        ),
        migrations.AddField(
            model_name='labservice',
            name='qc_reference_range',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='labservice',
            name='reference_range',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='labservice',
            name='result_input_type',
            field=models.CharField(choices=[('numeric_entry', 'Numeric Entry'), ('text_entry', 'Text Entry'), ('dropdown_select', 'Dropdown Select'), ('positive_negative', 'Positive / Negative')], default='numeric_entry', max_length=20),
        ),
        migrations.AddField(
            model_name='labservice',
            name='result_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('qualitative', 'Qualitative'), ('select', 'Select List'), ('free_text', 'Free Text')], default='numeric', max_length=15),
        ),
        migrations.AddField(
            model_name='labservice',
            name='stock_item_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='labservice',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='labservice',
            name='sample_type',
            field=models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Stool', 'Stool'), ('Swab', 'Swab'), ('Tissue', 'Tissue'), ('CSF', 'Cerebrospinal Fluid'), ('Sputum', 'Sputum'), ('Plasma', 'Plasma'), ('Serum', 'Serum'), ('Other', 'Other')], default='Blood', max_length=20),
        ),
        # Old `category` (free-text CharField, confirmed always blank in
        # practice) is removed outright rather than type-altered in place —
        # altering a varchar column directly to a FK/integer column requires
        # a manual USING cast and is unnecessary here since the field was
        # never populated.
        migrations.RemoveField(
            model_name='labservice',
            name='category',
        ),
        migrations.AddField(
            model_name='labservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_services', to='core.labcategory'),
        ),
        migrations.AddField(
            model_name='labtestgroup',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.labcategory'),
        ),
        migrations.AddField(
            model_name='labservice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_services', to='core.labtestgroup'),
        ),
        migrations.AddIndex(
            model_name='labservice',
            index=models.Index(fields=['is_active', 'category'], name='core_labser_is_acti_28aea2_idx'),
        ),
        migrations.AddField(
            model_name='labtestresultoption',
            name='lab_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_options', to='core.labservice'),
        ),
        # Backfill `category` from the about-to-be-removed `section` column
        # (via raw SQL against the DB, before Django's ORM state loses the
        # `section` field) — must run after `category` exists as a FK and
        # before `section` is dropped.
        migrations.RunPython(backfill_category_from_section, noop_reverse),
        migrations.RemoveField(
            model_name='labservice',
            name='section',
        ),
    ]
