# Generated by Django 6.0.6 on 2026-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_lab_catalog_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='labservice',
            name='analyzer',
            field=models.CharField(blank=True, help_text='e.g. Huma Count 30TS, Linear, ECL105', max_length=100),
        ),
    ]
