# Generated by Django 6.0.6 on 2026-07-09 14:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_lab_order_resulted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FallRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_of_falling', models.PositiveSmallIntegerField(choices=[(0, 'No'), (25, 'Yes')], default=0)),
                ('secondary_diagnosis', models.PositiveSmallIntegerField(choices=[(0, 'No'), (15, 'Yes')], default=0)),
                ('ambulatory_aid', models.PositiveSmallIntegerField(choices=[(0, 'None / Bed Rest / Nurse Assist'), (15, 'Crutches / Cane / Walker'), (30, 'Furniture')], default=0)),
                ('iv_therapy', models.PositiveSmallIntegerField(choices=[(0, 'No'), (20, 'Yes')], default=0)),
                ('gait', models.PositiveSmallIntegerField(choices=[(0, 'Normal / Bed Rest / Wheelchair'), (10, 'Weak'), (20, 'Impaired')], default=0)),
                ('mental_status', models.PositiveSmallIntegerField(choices=[(0, 'Oriented to Own Ability'), (15, 'Overestimates / Forgets Limitations')], default=0)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fall Risk Assessment',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FluidBalanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=10)),
                ('intake_oral', models.DecimalField(decimal_places=1, default=0, help_text='mL', max_digits=7)),
                ('intake_iv', models.DecimalField(decimal_places=1, default=0, help_text='mL', max_digits=7)),
                ('intake_other', models.DecimalField(decimal_places=1, default=0, help_text='mL', max_digits=7)),
                ('output_urine', models.DecimalField(decimal_places=1, default=0, help_text='mL', max_digits=7)),
                ('output_drain', models.DecimalField(decimal_places=1, default=0, help_text='mL', max_digits=7)),
                ('output_other', models.DecimalField(decimal_places=1, default=0, help_text='mL', max_digits=7)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fluid Balance / Intake & Output Record',
                'ordering': ['-record_date', '-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='GlasgowComaScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_opening', models.PositiveSmallIntegerField(choices=[(1, '1 — None'), (2, '2 — To Pain'), (3, '3 — To Speech'), (4, '4 — Spontaneous')], default=4)),
                ('verbal_response', models.PositiveSmallIntegerField(choices=[(1, '1 — None'), (2, '2 — Incomprehensible Sounds'), (3, '3 — Inappropriate Words'), (4, '4 — Confused'), (5, '5 — Oriented')], default=5)),
                ('motor_response', models.PositiveSmallIntegerField(choices=[(1, '1 — None'), (2, '2 — Extension to Pain'), (3, '3 — Abnormal Flexion'), (4, '4 — Withdrawal from Pain'), (5, '5 — Localizes Pain'), (6, '6 — Obeys Commands')], default=6)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Glasgow Coma Scale',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('initial', 'Initial Nursing Assessment'), ('daily', 'Daily Nursing Assessment')], default='daily', max_length=10)),
                ('general_appearance', models.CharField(blank=True, max_length=150)),
                ('level_of_consciousness', models.CharField(blank=True, max_length=100)),
                ('skin_condition', models.CharField(blank=True, max_length=150)),
                ('mobility', models.CharField(blank=True, max_length=150)),
                ('respiratory_status', models.CharField(blank=True, max_length=150)),
                ('cardiovascular_status', models.CharField(blank=True, max_length=150)),
                ('elimination_status', models.CharField(blank=True, max_length=150)),
                ('psychosocial_status', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nursing Assessment',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingCarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=300)),
                ('goal', models.CharField(max_length=300)),
                ('interventions', models.TextField()),
                ('evaluation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ongoing', 'Ongoing'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nursing Care Plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingHandoverNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=10)),
                ('handover_date', models.DateField(default=django.utils.timezone.localdate)),
                ('content', models.TextField()),
                ('priority_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nursing Handover Note',
                'ordering': ['-handover_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi_score', models.PositiveSmallIntegerField(choices=[(0, 'BMI > 20 (0)'), (1, 'BMI 18.5 - 20 (1)'), (2, 'BMI < 18.5 (2)')], default=0)),
                ('weight_loss_score', models.PositiveSmallIntegerField(choices=[(0, 'Unplanned weight loss < 5% (0)'), (1, '5 - 10% (1)'), (2, '> 10% (2)')], default=0)),
                ('acute_disease_score', models.PositiveSmallIntegerField(choices=[(0, 'No (0)'), (2, 'Acutely ill and no nutritional intake > 5 days (2)')], default=0)),
                ('dietary_notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nutritional Assessment (MUST)',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PainAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('location', models.CharField(blank=True, max_length=150)),
                ('character', models.CharField(blank=True, choices=[('sharp', 'Sharp'), ('dull', 'Dull'), ('burning', 'Burning'), ('throbbing', 'Throbbing'), ('cramping', 'Cramping'), ('other', 'Other')], max_length=15)),
                ('onset', models.CharField(blank=True, max_length=100)),
                ('intervention', models.CharField(blank=True, max_length=200)),
                ('reassessment_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pain Assessment',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PressureUlcerAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensory_perception', models.PositiveSmallIntegerField(choices=[(1, '1 — Most Severe'), (2, '2'), (3, '3'), (4, '4 — No Impairment')], default=4)),
                ('moisture', models.PositiveSmallIntegerField(choices=[(1, '1 — Most Severe'), (2, '2'), (3, '3'), (4, '4 — No Impairment')], default=4)),
                ('activity', models.PositiveSmallIntegerField(choices=[(1, '1 — Most Severe'), (2, '2'), (3, '3'), (4, '4 — No Impairment')], default=4)),
                ('mobility', models.PositiveSmallIntegerField(choices=[(1, '1 — Most Severe'), (2, '2'), (3, '3'), (4, '4 — No Impairment')], default=4)),
                ('nutrition', models.PositiveSmallIntegerField(choices=[(1, '1 — Most Severe'), (2, '2'), (3, '3'), (4, '4 — No Impairment')], default=4)),
                ('friction_shear', models.PositiveSmallIntegerField(choices=[(1, '1 — Problem'), (2, '2 — Potential Problem'), (3, '3 — No Apparent Problem')], default=3)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pressure Ulcer Risk Assessment (Braden)',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='hmspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_queue', 'Can manage patient queue'), ('perform_triage', 'Can perform triage assessment'), ('write_clinical_note', 'Can write clinical notes'), ('read_clinical_note', 'Can read clinical notes'), ('write_nursing_note', 'Can write nursing notes'), ('read_nursing_note', 'Can read nursing notes'), ('record_vital_signs', 'Can record vital signs'), ('read_vital_signs', 'Can read vital signs'), ('write_care_plan', 'Can write care plans'), ('read_care_plan', 'Can read care plans'), ('write_diagnosis', 'Can write diagnosis'), ('read_diagnosis', 'Can read diagnosis records'), ('write_prescription', 'Can write prescriptions'), ('read_prescription', 'Can read prescriptions'), ('request_lab_test', 'Can request laboratory tests'), ('read_lab_request', 'Can read lab requests'), ('process_lab_test', 'Can process lab tests / enter results'), ('write_lab_result', 'Can write lab results'), ('read_lab_result', 'Can read lab results'), ('collect_lab_sample', 'Can record sample collection'), ('release_lab_result', 'Can release lab results to patient'), ('manage_lab_services', 'Can manage lab service catalogue and pricing'), ('view_lab_reports', 'Can view laboratory management reports'), ('request_imaging', 'Can request imaging studies'), ('read_imaging_request', 'Can read imaging requests'), ('process_imaging', 'Can process imaging studies'), ('write_imaging_report', 'Can write imaging reports'), ('read_imaging_report', 'Can read imaging reports'), ('manage_imaging_services', 'Can manage imaging service catalogue and pricing'), ('write_anesthesia_record', 'Can write anesthesia records'), ('read_anesthesia_record', 'Can read anesthesia records'), ('read_billing', 'Can read billing records'), ('create_invoice', 'Can create invoices'), ('manage_billing', 'Can manage all billing records'), ('process_payment', 'Can process payments'), ('approve_credit_invoice', 'Can approve credit invoices'), ('manage_cash_sessions', 'Can open and close cash sessions'), ('read_financial_report', 'Can read financial reports'), ('read_medication_inventory', 'Can read medication inventory'), ('manage_medication', 'Can manage medication inventory'), ('dispense_medication', 'Can dispense medications'), ('read_prescription_for_dispensing', 'Can read prescriptions for dispensing'), ('process_pharmacy_sale', 'Can process pharmacy sales'), ('approve_pharmacy_discount', 'Can approve pharmacy discounts'), ('approve_credit_sale', 'Can approve credit pharmacy sales'), ('manage_pharmacy_returns', 'Can process pharmacy returns/refunds'), ('read_pharmacy_reports', 'Can view pharmacy sales reports'), ('view_dept_inventory', 'Can view department store inventory'), ('manage_dept_stores', 'Can create and edit department stores'), ('request_medication_transfer', 'Can request medication/consumable transfers'), ('approve_medication_transfer', 'Can approve / fulfill medication/consumable transfers'), ('ward_supervisor_approve', 'Can give ward-supervisor pre-approval on transfer requests'), ('record_dept_usage', 'Can record medication/consumable usage in department'), ('view_dept_reports', 'Can view department pharmacy reports'), ('view_nursing_dashboard', 'Can view the nursing dashboard'), ('manage_med_catalog', 'Can manage medication catalog'), ('receive_stock', 'Can receive stock / create batches'), ('manage_suppliers', 'Can manage suppliers'), ('view_inv_reports', 'Can view inventory reports'), ('export_inv_reports', 'Can export inventory reports'), ('read_inventory', 'Can read store inventory'), ('manage_inventory', 'Can manage store inventory'), ('create_purchase_order', 'Can create purchase orders'), ('approve_purchase_order', 'Can approve purchase orders'), ('create_purchase_request', 'Can create purchase requests'), ('approve_purchase_request', 'Can approve purchase requests'), ('issue_inventory', 'Can issue items from store'), ('manage_inventory_batches', 'Can receive and manage inventory batches'), ('manage_equipment_assets', 'Can manage equipment and asset records'), ('perform_stock_count', 'Can perform physical stock count'), ('approve_stock_count', 'Can approve stock count results'), ('view_store_reports', 'Can view store reports'), ('export_store_reports', 'Can export store reports'), ('manage_inventory_periods', 'Can open and close inventory periods (annual/quarterly/monthly)'), ('read_employee', 'Can read employee records'), ('manage_employees', 'Can manage employee records'), ('manage_attendance', 'Can manage attendance'), ('manage_payroll', 'Can manage payroll'), ('manage_employee_signatures', 'Can upload/replace signatures for any employee'), ('delete_employee_signature', 'Can remove (deactivate) an employee signature'), ('read_appointment', 'Can read appointments'), ('manage_appointments', 'Can manage appointments'), ('manage_doctor_availability', 'Can manage doctor schedules and availability'), ('view_appointment_reports', 'Can view appointment reports'), ('export_appointment_reports', 'Can export appointment reports'), ('read_clinical_reports', 'Can read clinical reports'), ('read_department_reports', 'Can read department reports'), ('manage_users', 'Can manage system users'), ('manage_roles', 'Can manage roles and permissions'), ('system_configuration', 'Can access system configuration'), ('read_audit_log', 'Can read audit logs'), ('manage_departments', 'Can manage departments'), ('view_patient_flow', 'Can view the patient flow dashboard'), ('manage_patient_flow', 'Can update patient journey status'), ('manage_discharge', 'Can create and manage discharge summaries'), ('view_dept_worklist', 'Can view department work list'), ('manage_procedure_master', 'Can manage procedure/surgery master list'), ('order_surgery', 'Can create and manage surgery orders'), ('approve_surgery_order', 'Can approve or reject surgery orders'), ('manage_or_schedule', 'Can manage OR schedule and room assignments'), ('write_surgery_anesthesia', 'Can write surgery anesthesia records'), ('read_surgery', 'Can read surgery orders and records'), ('write_operative_note', 'Can write operative notes'), ('manage_surgery_consumables', 'Can manage surgery consumables and supplies'), ('generate_surgery_billing', 'Can generate billing from surgery orders'), ('read_surgery_reports', 'Can read surgery reports'), ('write_postop_note', 'Can write post-operative notes'), ('read_postop_note', 'Can read post-operative notes'), ('add_periop_nursing_note', 'Can add nursing addenda to perioperative documents'), ('read_periop_document_history', 'Can view perioperative document version history'), ('manage_facilities', 'Can add, edit, and delete buildings, wards, rooms, beds, and OR configuration'), ('view_facility', 'Can view facility lists and dashboard'), ('assign_bed', 'Can admit, transfer, and discharge patients to/from beds'), ('view_facility_reports', 'Can view facility management reports'), ('manage_card_types', 'Can create, edit, and deactivate card types and consultation types'), ('override_card_expiry', 'Can waive the card renewal fee for an expired/missing card'), ('view_card_reports', 'Can view card and consultation type reports'), ('manage_specializations', 'Can create, edit, and deactivate medical specializations'), ('manage_doctors', 'Can create and edit doctor staff records'), ('view_specialization_reports', 'Can view specialization reports')], 'verbose_name': 'HMS Permission', 'verbose_name_plural': 'HMS Permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='departmentstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='admission',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('high', 'High'), ('critical', 'Critical')], default='routine', max_length=10),
        ),
        migrations.AddField(
            model_name='departmentstock',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_stocks', to='core.inventoryitem'),
        ),
        migrations.AddField(
            model_name='departmentstore',
            name='requires_ward_supervisor_approval',
            field=models.BooleanField(default=False, help_text='Requests from this store need a Ward Supervisor sign-off before pharmacy/store review.'),
        ),
        migrations.AddField(
            model_name='departmenttransferitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventoryitem'),
        ),
        migrations.AddField(
            model_name='departmentusage',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_usages', to='core.inventoryitem'),
        ),
        migrations.AddField(
            model_name='departmentusage',
            name='invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_usage', to='core.invoiceitem'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_billable',
            field=models.BooleanField(default=False, help_text='Charge the patient (at selling_price) when a nurse records usage of this item.'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='ward_supervisor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='ward_supervisor_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_ward_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferrequestitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventoryitem'),
        ),
        migrations.AddField(
            model_name='transferrequestitem',
            name='quantity_issued',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='departmentstock',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_stocks', to='core.medication'),
        ),
        migrations.AlterField(
            model_name='departmenttransferitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='departmenttransferitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departmenttransferitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medication'),
        ),
        migrations.AlterField(
            model_name='departmentusage',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_usages', to='core.medication'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('pending_ward_approval', 'Pending Ward Supervisor Approval'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('partial', 'Partially Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='transferrequestitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medication'),
        ),
        migrations.AddConstraint(
            model_name='departmentstock',
            constraint=models.UniqueConstraint(condition=models.Q(('medication__isnull', False)), fields=('department_store', 'medication'), name='uniq_dept_stock_medication'),
        ),
        migrations.AddConstraint(
            model_name='departmentstock',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_item__isnull', False)), fields=('department_store', 'inventory_item'), name='uniq_dept_stock_inventory_item'),
        ),
        migrations.AddField(
            model_name='fallriskassessment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fall_risk_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fallriskassessment',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fall_risk_assessments', to='core.visit'),
        ),
        migrations.AddField(
            model_name='fluidbalancerecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fluid_balance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fluidbalancerecord',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fluid_balance_records', to='core.visit'),
        ),
        migrations.AddField(
            model_name='glasgowcomascale',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='glasgow_coma_scales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='glasgowcomascale',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='glasgow_coma_scales', to='core.visit'),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_assessments', to='core.visit'),
        ),
        migrations.AddField(
            model_name='nursingcareplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_care_plans_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingcareplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_care_plans_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingcareplan',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_care_plans', to='core.visit'),
        ),
        migrations.AddField(
            model_name='nursinghandovernote',
            name='from_nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursinghandovernote',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_notes', to='core.patient'),
        ),
        migrations.AddField(
            model_name='nursinghandovernote',
            name='to_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursinghandovernote',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_notes', to='core.ward'),
        ),
        migrations.AddField(
            model_name='nutritionalassessment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nutritional_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nutritionalassessment',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nutritional_assessments', to='core.visit'),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pain_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pain_assessments', to='core.visit'),
        ),
        migrations.AddField(
            model_name='pressureulcerassessment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pressure_ulcer_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pressureulcerassessment',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pressure_ulcer_assessments', to='core.visit'),
        ),
    ]
