# Generated by Django 6.0.6 on 2026-07-09 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_nursing_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hmspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_queue', 'Can manage patient queue'), ('perform_triage', 'Can perform triage assessment'), ('write_clinical_note', 'Can write clinical notes'), ('read_clinical_note', 'Can read clinical notes'), ('write_nursing_note', 'Can write nursing notes'), ('read_nursing_note', 'Can read nursing notes'), ('record_vital_signs', 'Can record vital signs'), ('read_vital_signs', 'Can read vital signs'), ('write_care_plan', 'Can write care plans'), ('read_care_plan', 'Can read care plans'), ('write_diagnosis', 'Can write diagnosis'), ('read_diagnosis', 'Can read diagnosis records'), ('write_prescription', 'Can write prescriptions'), ('read_prescription', 'Can read prescriptions'), ('request_lab_test', 'Can request laboratory tests'), ('read_lab_request', 'Can read lab requests'), ('process_lab_test', 'Can process lab tests / enter results'), ('write_lab_result', 'Can write lab results'), ('read_lab_result', 'Can read lab results'), ('collect_lab_sample', 'Can record sample collection'), ('release_lab_result', 'Can release lab results to patient'), ('manage_lab_services', 'Can manage lab service catalogue and pricing'), ('view_lab_reports', 'Can view laboratory management reports'), ('request_imaging', 'Can request imaging studies'), ('read_imaging_request', 'Can read imaging requests'), ('process_imaging', 'Can process imaging studies'), ('write_imaging_report', 'Can write imaging reports'), ('read_imaging_report', 'Can read imaging reports'), ('manage_imaging_services', 'Can manage imaging service catalogue and pricing'), ('write_anesthesia_record', 'Can write anesthesia records'), ('read_anesthesia_record', 'Can read anesthesia records'), ('read_billing', 'Can read billing records'), ('create_invoice', 'Can create invoices'), ('manage_billing', 'Can manage all billing records'), ('process_payment', 'Can process payments'), ('approve_credit_invoice', 'Can approve credit invoices'), ('manage_cash_sessions', 'Can open and close cash sessions'), ('read_financial_report', 'Can read financial reports'), ('read_medication_inventory', 'Can read medication inventory'), ('manage_medication', 'Can manage medication inventory'), ('dispense_medication', 'Can dispense medications'), ('read_prescription_for_dispensing', 'Can read prescriptions for dispensing'), ('process_pharmacy_sale', 'Can process pharmacy sales'), ('approve_pharmacy_discount', 'Can approve pharmacy discounts'), ('approve_credit_sale', 'Can approve credit pharmacy sales'), ('manage_pharmacy_returns', 'Can process pharmacy returns/refunds'), ('read_pharmacy_reports', 'Can view pharmacy sales reports'), ('view_dept_inventory', 'Can view department store inventory'), ('manage_dept_stores', 'Can create and edit department stores'), ('request_medication_transfer', 'Can request medication/consumable transfers'), ('approve_medication_transfer', 'Can approve / fulfill medication/consumable transfers'), ('ward_supervisor_approve', 'Can give ward-supervisor pre-approval on transfer requests'), ('record_dept_usage', 'Can record medication/consumable usage in department'), ('view_dept_reports', 'Can view department pharmacy reports'), ('view_nursing_dashboard', 'Can view the nursing dashboard'), ('manage_med_catalog', 'Can manage medication catalog'), ('receive_stock', 'Can receive stock / create batches'), ('manage_suppliers', 'Can manage suppliers'), ('view_inv_reports', 'Can view inventory reports'), ('export_inv_reports', 'Can export inventory reports'), ('read_inventory', 'Can read store inventory'), ('manage_inventory', 'Can manage store inventory'), ('create_purchase_order', 'Can create purchase orders'), ('approve_purchase_order', 'Can approve purchase orders'), ('create_purchase_request', 'Can create purchase requests'), ('approve_purchase_request', 'Can approve purchase requests'), ('issue_inventory', 'Can issue items from store'), ('manage_inventory_batches', 'Can receive and manage inventory batches'), ('manage_equipment_assets', 'Can manage equipment and asset records'), ('perform_stock_count', 'Can perform physical stock count'), ('approve_stock_count', 'Can approve stock count results'), ('view_store_reports', 'Can view store reports'), ('export_store_reports', 'Can export store reports'), ('manage_inventory_periods', 'Can open and close inventory periods (annual/quarterly/monthly)'), ('read_employee', 'Can read employee records'), ('manage_employees', 'Can manage employee records'), ('manage_attendance', 'Can manage attendance'), ('manage_payroll', 'Can manage payroll'), ('manage_employee_signatures', 'Can upload/replace signatures for any employee'), ('delete_employee_signature', 'Can remove (deactivate) an employee signature'), ('read_appointment', 'Can read appointments'), ('manage_appointments', 'Can manage appointments'), ('manage_doctor_availability', 'Can manage doctor schedules and availability'), ('view_appointment_reports', 'Can view appointment reports'), ('export_appointment_reports', 'Can export appointment reports'), ('read_clinical_reports', 'Can read clinical reports'), ('read_department_reports', 'Can read department reports'), ('manage_users', 'Can manage system users'), ('manage_roles', 'Can manage roles and permissions'), ('system_configuration', 'Can access system configuration'), ('read_audit_log', 'Can read audit logs'), ('manage_departments', 'Can manage departments'), ('view_patient_flow', 'Can view the patient flow dashboard'), ('manage_patient_flow', 'Can update patient journey status'), ('manage_discharge', 'Can create and manage discharge summaries'), ('view_dept_worklist', 'Can view department work list'), ('manage_procedure_master', 'Can manage procedure/surgery master list'), ('order_surgery', 'Can create and manage surgery orders'), ('approve_surgery_order', 'Can approve or reject surgery orders'), ('manage_or_schedule', 'Can manage OR schedule and room assignments'), ('write_surgery_anesthesia', 'Can write surgery anesthesia records'), ('read_surgery', 'Can read surgery orders and records'), ('write_operative_note', 'Can write operative notes'), ('manage_surgery_consumables', 'Can manage surgery consumables and supplies'), ('generate_surgery_billing', 'Can generate billing from surgery orders'), ('read_surgery_reports', 'Can read surgery reports'), ('write_postop_note', 'Can write post-operative notes'), ('read_postop_note', 'Can read post-operative notes'), ('add_periop_nursing_note', 'Can add nursing addenda to perioperative documents'), ('read_periop_document_history', 'Can view perioperative document version history'), ('manage_facilities', 'Can add, edit, and delete buildings, wards, rooms, beds, and OR configuration'), ('view_facility', 'Can view facility lists and dashboard'), ('assign_bed', 'Can admit, transfer, and discharge patients to/from beds'), ('view_facility_reports', 'Can view facility management reports'), ('request_admission', 'Can create formal admission requests'), ('review_admission_request', 'Can approve or reject pending admission requests'), ('view_admission_dashboard', 'Can view the admission dashboard'), ('view_admission_reports', 'Can view admission management reports'), ('manage_deposit_rules', 'Can create and edit admission deposit rules'), ('manage_card_types', 'Can create, edit, and deactivate card types and consultation types'), ('override_card_expiry', 'Can waive the card renewal fee for an expired/missing card'), ('view_card_reports', 'Can view card and consultation type reports'), ('manage_specializations', 'Can create, edit, and deactivate medical specializations'), ('manage_doctors', 'Can create and edit doctor staff records'), ('view_specialization_reports', 'Can view specialization reports')], 'verbose_name': 'HMS Permission', 'verbose_name_plural': 'HMS Permissions'},
        ),
        migrations.AddField(
            model_name='admission',
            name='discharge_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='discharge_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_discharges_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('patient', 'Patient'), ('appointment', 'Appointment'), ('visit', 'Visit'), ('doctor', 'Doctor / Clinical'), ('nursing', 'Nursing'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('med_inventory', 'Medication Inventory'), ('dept_pharmacy', 'Dept Pharmacy'), ('inventory', 'Store & Inventory'), ('billing', 'Billing'), ('payment', 'Payment'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('admin', 'Administration'), ('auth', 'Authentication'), ('user', 'User Management'), ('anesthesia', 'Anesthesia'), ('queue', 'Queue / Triage'), ('surgery', 'Surgery'), ('facility', 'Facility Management'), ('card_management', 'Card & Consultation Type Management'), ('admission', 'Admission Management')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='service_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Laboratory', 'Laboratory'), ('Imaging', 'Imaging'), ('Medication', 'Medication'), ('Procedure', 'Procedure'), ('Bed / Room', 'Bed / Room'), ('Deposit', 'Admission Deposit'), ('Nursing Care', 'Nursing Care'), ('Service Charge', 'Service Charge'), ('Card Fee', 'Card Fee'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.CreateModel(
            name='AdmissionDepositRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(blank=True, choices=[('routine', 'Routine'), ('high', 'High'), ('critical', 'Critical')], help_text='Leave blank to match any priority.', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_exempt', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_rules', to='core.department')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_rules', to='core.ward')),
            ],
            options={
                'verbose_name': 'Admission Deposit Rule',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_diagnosis', models.CharField(max_length=255)),
                ('reason_for_admission', models.TextField()),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=10)),
                ('expected_los_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Expected length of stay (days)')),
                ('requires_isolation', models.BooleanField(default=False)),
                ('requires_icu', models.BooleanField(default=False)),
                ('requires_oxygen', models.BooleanField(default=False)),
                ('special_requirements_notes', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('request_source', models.CharField(choices=[('reception', 'Reception'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('emergency', 'Emergency Department'), ('or', 'Operating Room')], default='reception', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Admission'), ('approved', 'Approved'), ('awaiting_deposit', 'Awaiting Deposit'), ('deposit_paid', 'Deposit Paid'), ('credit_approved', 'Credit Approved'), ('awaiting_bed', 'Awaiting Bed'), ('admitted', 'Admitted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitting_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests', to='core.department')),
                ('admitting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests', to='core.doctor')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests_cancelled', to=settings.AUTH_USER_MODEL)),
                ('deposit_invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_for_requests', to='core.invoiceitem')),
                ('deposit_rule_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_applied_to', to='core.admissiondepositrule')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests', to='core.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests', to='core.visit')),
            ],
            options={
                'verbose_name': 'Admission Request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission', to='core.admissionrequest'),
        ),
    ]
