# Generated by Django 6.0.6 on 2026-07-16 09:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_patient_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hmspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_queue', 'Can manage patient queue'), ('perform_triage', 'Can perform triage assessment'), ('write_clinical_note', 'Can write clinical notes'), ('read_clinical_note', 'Can read clinical notes'), ('write_nursing_note', 'Can write nursing notes'), ('read_nursing_note', 'Can read nursing notes'), ('record_vital_signs', 'Can record vital signs'), ('read_vital_signs', 'Can read vital signs'), ('write_care_plan', 'Can write care plans'), ('read_care_plan', 'Can read care plans'), ('write_diagnosis', 'Can write diagnosis'), ('read_diagnosis', 'Can read diagnosis records'), ('write_prescription', 'Can write prescriptions'), ('read_prescription', 'Can read prescriptions'), ('request_lab_test', 'Can request laboratory tests'), ('read_lab_request', 'Can read lab requests'), ('process_lab_test', 'Can process lab tests / enter results'), ('write_lab_result', 'Can write lab results'), ('read_lab_result', 'Can read lab results'), ('collect_lab_sample', 'Can record sample collection'), ('release_lab_result', 'Can release lab results to patient'), ('manage_lab_services', 'Can manage lab service catalogue and pricing'), ('view_lab_reports', 'Can view laboratory management reports'), ('request_imaging', 'Can request imaging studies'), ('read_imaging_request', 'Can read imaging requests'), ('process_imaging', 'Can process imaging studies'), ('write_imaging_report', 'Can write imaging reports'), ('read_imaging_report', 'Can read imaging reports'), ('manage_imaging_services', 'Can manage imaging service catalogue and pricing'), ('write_anesthesia_record', 'Can write anesthesia records'), ('read_anesthesia_record', 'Can read anesthesia records'), ('read_billing', 'Can read billing records'), ('create_invoice', 'Can create invoices'), ('manage_billing', 'Can manage all billing records'), ('process_payment', 'Can process payments'), ('approve_credit_invoice', 'Can approve credit invoices'), ('manage_cash_sessions', 'Can open and close cash sessions'), ('read_financial_report', 'Can read financial reports'), ('read_medication_inventory', 'Can read medication inventory'), ('manage_medication', 'Can manage medication inventory'), ('dispense_medication', 'Can dispense medications'), ('read_prescription_for_dispensing', 'Can read prescriptions for dispensing'), ('process_pharmacy_sale', 'Can process pharmacy sales'), ('approve_pharmacy_discount', 'Can approve pharmacy discounts'), ('approve_credit_sale', 'Can approve credit pharmacy sales'), ('manage_pharmacy_returns', 'Can process pharmacy returns/refunds'), ('read_pharmacy_reports', 'Can view pharmacy sales reports'), ('view_dept_inventory', 'Can view department store inventory'), ('manage_dept_stores', 'Can create and edit department stores'), ('request_medication_transfer', 'Can request medication/consumable transfers'), ('approve_medication_transfer', 'Can approve / fulfill medication/consumable transfers'), ('ward_supervisor_approve', 'Can give ward-supervisor pre-approval on transfer requests'), ('record_dept_usage', 'Can record medication/consumable usage in department'), ('view_dept_reports', 'Can view department pharmacy reports'), ('view_nursing_dashboard', 'Can view the nursing dashboard'), ('manage_med_catalog', 'Can manage medication catalog'), ('receive_stock', 'Can receive stock / create batches'), ('manage_suppliers', 'Can manage suppliers'), ('view_inv_reports', 'Can view inventory reports'), ('export_inv_reports', 'Can export inventory reports'), ('manage_supplier_payments', 'Can record payments against supplier payables'), ('read_inventory', 'Can read store inventory'), ('manage_inventory', 'Can manage store inventory'), ('create_purchase_order', 'Can create purchase orders'), ('approve_purchase_order', 'Can approve purchase orders'), ('create_purchase_request', 'Can create purchase requests'), ('approve_purchase_request', 'Can approve purchase requests'), ('issue_inventory', 'Can issue items from store'), ('manage_inventory_batches', 'Can receive and manage inventory batches'), ('manage_equipment_assets', 'Can manage equipment and asset records'), ('perform_stock_count', 'Can perform physical stock count'), ('approve_stock_count', 'Can approve stock count results'), ('view_store_reports', 'Can view store reports'), ('export_store_reports', 'Can export store reports'), ('manage_inventory_periods', 'Can open and close inventory periods (annual/quarterly/monthly)'), ('read_employee', 'Can read employee records'), ('manage_employees', 'Can manage employee records'), ('manage_attendance', 'Can manage attendance'), ('manage_payroll', 'Can manage payroll'), ('manage_employee_signatures', 'Can upload/replace signatures for any employee'), ('delete_employee_signature', 'Can remove (deactivate) an employee signature'), ('read_appointment', 'Can read appointments'), ('manage_appointments', 'Can manage appointments'), ('manage_doctor_availability', 'Can manage doctor schedules and availability'), ('view_appointment_reports', 'Can view appointment reports'), ('export_appointment_reports', 'Can export appointment reports'), ('read_clinical_reports', 'Can read clinical reports'), ('read_department_reports', 'Can read department reports'), ('manage_users', 'Can manage system users'), ('manage_roles', 'Can manage roles and permissions'), ('system_configuration', 'Can access system configuration'), ('read_audit_log', 'Can read audit logs'), ('manage_departments', 'Can manage departments'), ('view_patient_flow', 'Can view the patient flow dashboard'), ('manage_patient_flow', 'Can update patient journey status'), ('manage_discharge', 'Can create and manage discharge summaries'), ('view_dept_worklist', 'Can view department work list'), ('manage_procedure_master', 'Can manage procedure/surgery master list'), ('order_surgery', 'Can create and manage surgery orders'), ('approve_surgery_order', 'Can approve or reject surgery orders'), ('manage_or_schedule', 'Can manage OR schedule and room assignments'), ('write_surgery_anesthesia', 'Can write surgery anesthesia records'), ('read_surgery', 'Can read surgery orders and records'), ('write_operative_note', 'Can write operative notes'), ('manage_surgery_consumables', 'Can manage surgery consumables and supplies'), ('generate_surgery_billing', 'Can generate billing from surgery orders'), ('read_surgery_reports', 'Can read surgery reports'), ('write_postop_note', 'Can write post-operative notes'), ('read_postop_note', 'Can read post-operative notes'), ('add_periop_nursing_note', 'Can add nursing addenda to perioperative documents'), ('read_periop_document_history', 'Can view perioperative document version history'), ('manage_facilities', 'Can add, edit, and delete buildings, wards, rooms, beds, and OR configuration'), ('view_facility', 'Can view facility lists and dashboard'), ('assign_bed', 'Can admit, transfer, and discharge patients to/from beds'), ('view_facility_reports', 'Can view facility management reports'), ('request_admission', 'Can create formal admission requests'), ('review_admission_request', 'Can approve or reject pending admission requests'), ('view_admission_dashboard', 'Can view the admission dashboard'), ('view_admission_reports', 'Can view admission management reports'), ('manage_deposit_rules', 'Can create and edit admission deposit rules'), ('upload_attachment', 'Can upload patient documents/attachments'), ('view_attachments', 'Can view patient documents/attachments'), ('view_confidential_attachments', 'Can view documents marked confidential'), ('replace_attachment', 'Can replace an attachment with a new version'), ('delete_attachment', 'Can delete (soft-delete) a patient attachment'), ('restore_attachment', 'Can restore a deleted patient attachment'), ('manage_attachment_categories', 'Can create, edit, and deactivate attachment categories'), ('view_attachment_reports', 'Can view attachment/document management reports'), ('manage_card_types', 'Can create, edit, and deactivate card types and consultation types'), ('override_card_expiry', 'Can waive the card renewal fee for an expired/missing card'), ('view_card_reports', 'Can view card and consultation type reports'), ('manage_specializations', 'Can create, edit, and deactivate medical specializations'), ('manage_doctors', 'Can create and edit doctor staff records'), ('view_specialization_reports', 'Can view specialization reports')], 'verbose_name': 'HMS Permission', 'verbose_name_plural': 'HMS Permissions'},
        ),
        migrations.AddField(
            model_name='medicationbatch',
            name='ownership',
            field=models.CharField(choices=[('purchased', 'Purchased'), ('consignment', 'Consignment')], default='purchased', max_length=15),
        ),
        migrations.AddField(
            model_name='medicationbatch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicationbatch',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('quarantine', 'Quarantined'), ('recalled', 'Recalled')], default='active', max_length=15),
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_receipt_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('supplier_invoice_number', models.CharField(max_length=100)),
                ('supplier_invoice_date', models.DateField(blank=True, null=True)),
                ('purchase_order_ref', models.CharField(blank=True, max_length=100)),
                ('delivery_note_number', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('consignment', 'Consignment')], default='cash', max_length=15)),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cash_payment_date', models.DateField(blank=True, null=True)),
                ('cash_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts_cashiered', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts_received', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Goods Receipt',
                'ordering': ['-received_date'],
                'unique_together': {('supplier', 'supplier_invoice_number')},
            },
        ),
        migrations.AddField(
            model_name='medicationbatch',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.goodsreceipt'),
        ),
        migrations.CreateModel(
            name='PharmacyCreditSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_days_before_due', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_credit_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacy Credit Settings',
                'verbose_name_plural': 'Pharmacy Credit Settings',
            },
        ),
        migrations.CreateModel(
            name='SupplierPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('credit_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('consignment_agreement_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goods_receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payable', to='core.goodsreceipt')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Payable',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.supplierpayable')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Payment',
                'ordering': ['-payment_date'],
            },
        ),
    ]
