# Generated by Django 6.0.6 on 2026-07-16 11:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_goods_receipt_and_payables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='selling_price_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='selling_price_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationbatch',
            name='selling_price_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pricing Settings',
                'verbose_name_plural': 'Pricing Settings',
            },
        ),
    ]
