# Generated by Django 6.0.6 on 2026-07-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_pricing_settings_and_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medication',
            name='atc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='inventory_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_details', to='core.inventoryitem'),
        ),
    ]
