# Generated by Django 6.0.6 on 2026-07-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_inventory_item_master_step3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['brand_name']},
        ),
    ]
