from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

_ALL_PERMS = [
    ('manage_queue', 'Can manage patient queue'),
    ('perform_triage', 'Can perform triage assessment'),
    ('write_clinical_note', 'Can write clinical notes'),
    ('read_clinical_note', 'Can read clinical notes'),
    ('write_nursing_note', 'Can write nursing notes'),
    ('read_nursing_note', 'Can read nursing notes'),
    ('record_vital_signs', 'Can record vital signs'),
    ('read_vital_signs', 'Can read vital signs'),
    ('write_care_plan', 'Can write care plans'),
    ('read_care_plan', 'Can read care plans'),
    ('write_diagnosis', 'Can write diagnosis'),
    ('read_diagnosis', 'Can read diagnosis records'),
    ('write_prescription', 'Can write prescriptions'),
    ('read_prescription', 'Can read prescriptions'),
    ('request_lab_test', 'Can request laboratory tests'),
    ('read_lab_request', 'Can read lab requests'),
    ('process_lab_test', 'Can process lab tests / enter results'),
    ('write_lab_result', 'Can write lab results'),
    ('read_lab_result', 'Can read lab results'),
    ('collect_lab_sample', 'Can record sample collection'),
    ('release_lab_result', 'Can release lab results to patient'),
    ('manage_lab_services', 'Can manage lab service catalogue and pricing'),
    ('view_lab_reports', 'Can view laboratory management reports'),
    ('request_imaging', 'Can request imaging studies'),
    ('read_imaging_request', 'Can read imaging requests'),
    ('process_imaging', 'Can process imaging studies'),
    ('write_imaging_report', 'Can write imaging reports'),
    ('read_imaging_report', 'Can read imaging reports'),
    ('manage_imaging_services', 'Can manage imaging service catalogue and pricing'),
    ('write_anesthesia_record', 'Can write anesthesia records'),
    ('read_anesthesia_record', 'Can read anesthesia records'),
    ('read_billing', 'Can read billing records'),
    ('create_invoice', 'Can create invoices'),
    ('manage_billing', 'Can manage all billing records'),
    ('process_payment', 'Can process payments'),
    ('approve_credit_invoice', 'Can approve credit invoices'),
    ('manage_cash_sessions', 'Can open and close cash sessions'),
    ('read_financial_report', 'Can read financial reports'),
    ('read_medication_inventory', 'Can read medication inventory'),
    ('manage_medication', 'Can manage medication inventory'),
    ('dispense_medication', 'Can dispense medications'),
    ('read_prescription_for_dispensing', 'Can read prescriptions for dispensing'),
    ('process_pharmacy_sale', 'Can process pharmacy sales'),
    ('approve_pharmacy_discount', 'Can approve pharmacy discounts'),
    ('approve_credit_sale', 'Can approve credit pharmacy sales'),
    ('manage_pharmacy_returns', 'Can process pharmacy returns/refunds'),
    ('read_pharmacy_reports', 'Can view pharmacy sales reports'),
    ('view_dept_inventory', 'Can view department store inventory'),
    ('manage_dept_stores', 'Can create and edit department stores'),
    ('request_medication_transfer', 'Can request medication/consumable transfers'),
    ('approve_medication_transfer', 'Can approve / fulfill medication/consumable transfers'),
    ('ward_supervisor_approve', 'Can give ward-supervisor pre-approval on transfer requests'),
    ('record_dept_usage', 'Can record medication/consumable usage in department'),
    ('view_dept_reports', 'Can view department pharmacy reports'),
    ('view_patient_requisitions', 'Can view patient-specific requisitions'),
    ('manage_patient_requisitions', 'Can create and manage patient-specific requisitions'),
    ('view_nursing_dashboard', 'Can view the nursing dashboard'),
    ('manage_med_catalog', 'Can manage medication catalog'),
    ('receive_stock', 'Can receive stock / create batches'),
    ('manage_suppliers', 'Can manage suppliers'),
    ('view_inv_reports', 'Can view inventory reports'),
    ('export_inv_reports', 'Can export inventory reports'),
    ('manage_supplier_payments', 'Can record payments against supplier payables'),
    ('read_inventory', 'Can read store inventory'),
    ('manage_inventory', 'Can manage store inventory'),
    ('create_purchase_order', 'Can create purchase orders'),
    ('approve_purchase_order', 'Can approve purchase orders'),
    ('create_purchase_request', 'Can create purchase requests'),
    ('approve_purchase_request', 'Can approve purchase requests'),
    ('issue_inventory', 'Can issue items from store'),
    ('manage_inventory_batches', 'Can receive and manage inventory batches'),
    ('manage_equipment_assets', 'Can manage equipment and asset records'),
    ('perform_stock_count', 'Can perform physical stock count'),
    ('approve_stock_count', 'Can approve stock count results'),
    ('view_store_reports', 'Can view store reports'),
    ('export_store_reports', 'Can export store reports'),
    ('manage_inventory_periods', 'Can open and close inventory periods (annual/quarterly/monthly)'),
    ('read_employee', 'Can read employee records'),
    ('manage_employees', 'Can manage employee records'),
    ('manage_attendance', 'Can manage attendance'),
    ('manage_payroll', 'Can manage payroll'),
    ('manage_employee_signatures', 'Can upload/replace signatures for any employee'),
    ('delete_employee_signature', 'Can remove (deactivate) an employee signature'),
    ('read_appointment', 'Can read appointments'),
    ('manage_appointments', 'Can manage appointments'),
    ('manage_doctor_availability', 'Can manage doctor schedules and availability'),
    ('view_appointment_reports', 'Can view appointment reports'),
    ('export_appointment_reports', 'Can export appointment reports'),
    ('read_clinical_reports', 'Can read clinical reports'),
    ('read_department_reports', 'Can read department reports'),
    ('manage_users', 'Can manage system users'),
    ('manage_roles', 'Can manage roles and permissions'),
    ('system_configuration', 'Can access system configuration'),
    ('read_audit_log', 'Can read audit logs'),
    ('manage_departments', 'Can manage departments'),
    ('view_patient_flow', 'Can view the patient flow dashboard'),
    ('manage_patient_flow', 'Can update patient journey status'),
    ('manage_discharge', 'Can create and manage discharge summaries'),
    ('view_dept_worklist', 'Can view department work list'),
    ('manage_procedure_master', 'Can manage procedure/surgery master list'),
    ('order_surgery', 'Can create and manage surgery orders'),
    ('approve_surgery_order', 'Can approve or reject surgery orders'),
    ('manage_or_schedule', 'Can manage OR schedule and room assignments'),
    ('write_surgery_anesthesia', 'Can write surgery anesthesia records'),
    ('read_surgery', 'Can read surgery orders and records'),
    ('write_operative_note', 'Can write operative notes'),
    ('manage_surgery_consumables', 'Can manage surgery consumables and supplies'),
    ('generate_surgery_billing', 'Can generate billing from surgery orders'),
    ('read_surgery_reports', 'Can read surgery reports'),
    ('write_postop_note', 'Can write post-operative notes'),
    ('read_postop_note', 'Can read post-operative notes'),
    ('add_periop_nursing_note', 'Can add nursing addenda to perioperative documents'),
    ('read_periop_document_history', 'Can view perioperative document version history'),
    # New surgery booking workflow permissions
    ('counsel_surgery_patient', 'Can counsel patients about surgery cost and record patient decisions'),
    ('process_surgery_booking_deposit', 'Can process and record surgery booking deposits'),
    ('initiate_surgery_admission', 'Can initiate inpatient admission for surgical patients'),
    ('manage_facilities', 'Can add, edit, and delete buildings, wards, rooms, beds, and OR configuration'),
    ('view_facility', 'Can view facility lists and dashboard'),
    ('assign_bed', 'Can admit, transfer, and discharge patients to/from beds'),
    ('view_facility_reports', 'Can view facility management reports'),
    ('request_admission', 'Can create formal admission requests'),
    ('review_admission_request', 'Can approve or reject pending admission requests'),
    ('view_admission_dashboard', 'Can view the admission dashboard'),
    ('view_admission_reports', 'Can view admission management reports'),
    ('manage_deposit_rules', 'Can create and edit admission deposit rules'),
    ('view_inpatient_deposit', 'Can view inpatient deposit accounts and balances'),
    ('manage_inpatient_deposit', 'Can add deposits, adjustments, and process reconciliation'),
    ('view_deposit_reports', 'Can view inpatient deposit reports'),
    ('upload_attachment', 'Can upload patient documents/attachments'),
    ('view_attachments', 'Can view patient documents/attachments'),
    ('view_confidential_attachments', 'Can view documents marked confidential'),
    ('replace_attachment', 'Can replace an attachment with a new version'),
    ('delete_attachment', 'Can delete (soft-delete) a patient attachment'),
    ('restore_attachment', 'Can restore a deleted patient attachment'),
    ('manage_attachment_categories', 'Can create, edit, and deactivate attachment categories'),
    ('view_attachment_reports', 'Can view attachment/document management reports'),
    ('manage_card_types', 'Can create, edit, and deactivate card types and consultation types'),
    ('override_card_expiry', 'Can waive the card renewal fee for an expired/missing card'),
    ('view_card_reports', 'Can view card and consultation type reports'),
    ('manage_specializations', 'Can create, edit, and deactivate medical specializations'),
    ('manage_doctors', 'Can create and edit doctor staff records'),
    ('view_specialization_reports', 'Can view specialization reports'),
    ('write_medical_certificate', 'Can create and edit medical certificates'),
    ('finalize_medical_certificate', 'Can finalize and sign medical certificates'),
    ('read_medical_certificate', 'Can view and print medical certificates'),
    ('void_medical_certificate', 'Can void a finalized medical certificate'),
    ('write_death_certificate', 'Can create and edit death certificates'),
    ('finalize_death_certificate', 'Can finalize and sign death certificates'),
    ('read_death_certificate', 'Can view and print death certificates'),
    ('void_death_certificate', 'Can void a finalized death certificate'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_inpatient_deposit_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── HMSPermissions: add 3 surgery booking perms ───────────────────────
        migrations.AlterModelOptions(
            name='hmspermissions',
            options={
                'default_permissions': (),
                'managed': False,
                'permissions': _ALL_PERMS,
                'verbose_name': 'HMS Permission',
                'verbose_name_plural': 'HMS Permissions',
            },
        ),

        # ── InvoiceItem: add Surgery Booking service type ─────────────────────
        migrations.AlterField(
            model_name='invoiceitem',
            name='service_type',
            field=models.CharField(
                choices=[
                    ('Consultation', 'Consultation'),
                    ('Laboratory', 'Laboratory'),
                    ('Imaging', 'Imaging'),
                    ('Medication', 'Medication'),
                    ('Procedure', 'Procedure'),
                    ('Bed / Room', 'Bed / Room'),
                    ('Deposit', 'Admission Deposit'),
                    ('Nursing Care', 'Nursing Care'),
                    ('Service Charge', 'Service Charge'),
                    ('Card Fee', 'Card Fee'),
                    ('Surgery Booking', 'Surgery Booking Deposit'),
                    ('Other', 'Other'),
                ],
                default='Other',
                max_length=20,
            ),
        ),

        # ── SurgeryOrder: new status choices ─────────────────────────────────
        migrations.AlterField(
            model_name='surgeryorder',
            name='status',
            field=models.CharField(
                choices=[
                    ('ordered', 'Ordered'),
                    ('pending_review', 'Pending Review'),
                    ('approved', 'Approved'),
                    ('scheduled', 'Scheduled'),
                    ('patient_prepared', 'Patient Prepared'),
                    ('in_or', 'In Operating Room'),
                    ('completed', 'Completed'),
                    ('post_op', 'Post-operative Care'),
                    ('cancelled', 'Cancelled'),
                    ('awaiting_decision', 'Awaiting Patient Decision'),
                    ('booking_deposit', 'Booking Deposit Pending'),
                    ('awaiting_admission', 'Awaiting Inpatient Admission'),
                    ('recovery', 'Recovery'),
                    ('discharged', 'Discharged'),
                ],
                db_index=True,
                default='ordered',
                max_length=20,
            ),
        ),

        # ── SurgeryOrder: counseling fields ──────────────────────────────────
        migrations.AddField(
            model_name='surgeryorder',
            name='counseling_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='counseling_done_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='surgery_counselings',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='counseling_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # ── SurgeryOrder: patient decision fields ────────────────────────────
        migrations.AddField(
            model_name='surgeryorder',
            name='patient_decision',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('agreed', 'Agreed'), ('declined', 'Declined')],
                default='pending',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='patient_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='patient_decision_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='surgery_patient_decisions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='patient_decline_reason',
            field=models.TextField(blank=True),
        ),

        # ── SurgeryOrder: booking deposit fields ─────────────────────────────
        migrations.AddField(
            model_name='surgeryorder',
            name='booking_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='booking_deposit_invoice',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='surgery_booking_deposit_orders',
                to='core.invoice',
            ),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='booking_deposit_invoice_item',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='surgery_booking_deposit_order',
                to='core.invoiceitem',
            ),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='booking_deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='booking_deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # ── SurgeryOrder: admission bridge ───────────────────────────────────
        migrations.AddField(
            model_name='surgeryorder',
            name='surgery_admission_request',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='surgery_orders',
                to='core.admissionrequest',
            ),
        ),

        # ── SurgeryOrder: recovery / discharge timestamps ────────────────────
        migrations.AddField(
            model_name='surgeryorder',
            name='recovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='discharged_surgery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
