# Generated by Django 6.0.6 on 2026-07-17 18:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_surgery_booking_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryorder',
            name='estimated_anesthesia_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='estimated_facility_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='estimated_procedure_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='surgeryorder',
            name='estimated_surgeon_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
