# Generated by Django 6.0.6 on 2026-07-18 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_surgeryorder_estimated_fees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('specialty', models.CharField(choices=[('General', 'General / Internal Medicine'), ('Surgery', 'Surgery / Pre-Op'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology & Obstetrics'), ('Orthopedics', 'Orthopedics'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Neurology', 'Neurology'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Urology', 'Urology'), ('Emergency', 'Emergency Medicine'), ('Psychiatry', 'Psychiatry'), ('Custom', 'Custom')], default='General', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('systems_config', models.JSONField(default=list, help_text='List of {key, include, default_status}')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Physical Exam Template',
                'verbose_name_plural': 'Physical Exam Templates',
                'ordering': ['specialty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.JSONField(default=dict, help_text='system_key: {status, comment}')),
                ('overall_summary', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_note', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_exam', to='core.clinicalnote')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_exams_conducted', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_exams', to='core.visit')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='core.physicalexamtemplate')),
            ],
            options={
                'verbose_name': 'Physical Examination',
                'verbose_name_plural': 'Physical Examinations',
                'ordering': ['-created_at'],
            },
        ),
    ]
