# Generated by Django 6.0.6 on 2026-07-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_surgery_pre_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hospital Management System', max_length=200)),
                ('short_name', models.CharField(blank=True, help_text='Abbreviated name for tight spaces', max_length=60)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital/')),
                ('stamp', models.ImageField(blank=True, help_text='Official stamp/seal for documents', null=True, upload_to='hospital/')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('phone_alt', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='License Number')),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='TIN')),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('currency_symbol', models.CharField(default='ETB', max_length=5)),
                ('timezone', models.CharField(default='Africa/Addis_Ababa', max_length=60)),
                ('language', models.CharField(default='en', max_length=10)),
                ('report_header', models.TextField(blank=True, help_text='Shown at top of printed reports')),
                ('report_footer', models.TextField(blank=True, help_text='Shown at bottom of printed documents')),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex colour for UI accent', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Profile',
            },
        ),
        migrations.CreateModel(
            name='LicenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('license_key', models.CharField(max_length=255, unique=True)),
                ('license_type', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='standard', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('max_branches', models.PositiveIntegerField(default=1)),
                ('issued_at', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('support_expiration', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'License',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Unique machine-readable key', unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('clinical', 'Clinical'), ('diagnostic', 'Diagnostic'), ('operations', 'Operations'), ('administrative', 'Administrative'), ('financial', 'Financial'), ('hr', 'Human Resources')], default='administrative', max_length=20)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG path data for the module icon')),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_core', models.BooleanField(default=False, help_text='Core modules cannot be disabled')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'System Module',
                'ordering': ['category', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SystemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='SemVer e.g. 1.0.0', max_length=20)),
                ('build', models.CharField(blank=True, max_length=50)),
                ('release_date', models.DateField()),
                ('release_notes', models.TextField(blank=True)),
                ('db_schema_ver', models.CharField(blank=True, max_length=20, verbose_name='DB Schema Version')),
                ('api_version', models.CharField(blank=True, max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Version',
                'ordering': ['-release_date', '-id'],
            },
        ),
    ]
