from django.urls import path

from . import (
    views, views_admin, views_admissions, views_anesthesia, views_appointments, views_attachments,
    views_audit, views_billing,
    views_cards, views_dept_pharmacy, views_doctor, views_facility, views_hr, views_inventory,
    views_lab, views_med_inventory, views_nursing, views_or, views_patient_flow, views_pharmacy,
    views_pharmacy_pos, views_physical_count, views_prescription, views_queue, views_radiology,
    views_receptionist, views_reports, views_session, views_signatures, views_specialization,
    views_store, views_surgery,
)

urlpatterns = [
    # ── Core app ────────────────────────────────────────────────────────────
    path('', views.dashboard, name='dashboard'),
    path('register-patient/', views.register_patient, name='register_patient'),
    path('patient/<int:patient_id>/next-action/', views.patient_next_action, name='patient_next_action'),
    path('patient-search/', views.patient_search, name='patient_search'),
    path('create-visit/<int:patient_id>/', views.create_visit, name='create_visit'),
    path('access-denied/', views.access_denied, name='access_denied'),

    # ── User management ──────────────────────────────────────────────────────
    path('users/', views.user_list, name='user_list'),
    path('users/create/', views.user_create, name='user_create'),
    path('users/<int:user_id>/', views_admin.user_detail, name='user_detail'),
    path('users/<int:user_id>/edit/', views.user_edit, name='user_edit'),
    path('users/<int:user_id>/reset-password/', views.user_reset_password, name='user_reset_password'),
    path('users/<int:user_id>/toggle-active/', views.user_toggle_active, name='user_toggle_active'),

    # ── RBAC — Role management ─────────────────────────────────────────────
    path('settings/roles/', views_admin.role_list, name='role_list'),
    path('settings/roles/create/', views_admin.role_create, name='role_create'),
    path('settings/roles/<int:group_id>/', views_admin.role_detail, name='role_detail'),
    path('settings/roles/<int:group_id>/edit/', views_admin.role_permissions_edit, name='role_permissions_edit'),
    path('settings/roles/<int:group_id>/delete/', views_admin.role_delete, name='role_delete'),

    # ── RBAC — Department management ──────────────────────────────────────
    path('settings/departments/', views_admin.dept_list, name='dept_list'),
    path('settings/departments/create/', views_admin.dept_create, name='dept_create'),
    path('settings/departments/<int:dept_id>/edit/', views_admin.dept_edit, name='dept_edit'),
    path('settings/departments/<int:dept_id>/delete/', views_admin.dept_delete, name='dept_delete'),

    # ── Card Type & Consultation Type Management ──────────────────────────────
    path('settings/card-types/', views_cards.card_type_list, name='card_type_list'),
    path('settings/card-types/create/', views_cards.card_type_create, name='card_type_create'),
    path('settings/card-types/<int:card_type_id>/edit/', views_cards.card_type_edit, name='card_type_edit'),
    path('settings/card-types/<int:card_type_id>/toggle-active/', views_cards.card_type_toggle_active, name='card_type_toggle_active'),
    path('settings/consultation-types/', views_cards.consultation_type_list, name='consultation_type_list'),
    path('settings/consultation-types/create/', views_cards.consultation_type_create, name='consultation_type_create'),
    path('settings/consultation-types/<int:consultation_type_id>/edit/', views_cards.consultation_type_edit, name='consultation_type_edit'),
    path('settings/consultation-types/<int:consultation_type_id>/toggle-active/', views_cards.consultation_type_toggle_active, name='consultation_type_toggle_active'),
    path('settings/card-config/', views_cards.card_settings_edit, name='card_settings_edit'),
    path('patient/<int:patient_id>/cards/', views_cards.patient_card_history, name='patient_card_history'),
    path('patient/<int:patient_id>/cards/renew/', views_cards.patient_card_renew, name='patient_card_renew'),
    path('patient/<int:patient_id>/cards/status/', views_cards.card_status_check, name='card_status_check'),

    # ── Doctor Specialization Management ──────────────────────────────────────
    path('settings/specializations/', views_specialization.specialization_list, name='specialization_list'),
    path('settings/specializations/create/', views_specialization.specialization_create, name='specialization_create'),
    path('settings/specializations/<int:specialization_id>/edit/', views_specialization.specialization_edit, name='specialization_edit'),
    path('settings/specializations/<int:specialization_id>/toggle-active/', views_specialization.specialization_toggle_active, name='specialization_toggle_active'),
    path('settings/specializations/api/for-department/', views_specialization.specializations_for_department, name='specializations_for_department'),
    path('settings/doctors/', views_specialization.doctor_list, name='doctor_list'),
    path('settings/doctors/create/', views_specialization.doctor_create, name='doctor_create'),
    path('settings/doctors/<int:doctor_id>/edit/', views_specialization.doctor_edit, name='doctor_edit'),

    # ── Doctor module ─────────────────────────────────────────────────────────
    path('doctor/', views_doctor.doctor_dashboard, name='doctor_dashboard'),
    path('doctor/patients/', views_doctor.doctor_patient_list, name='doctor_patient_list'),
    path('doctor/visit/<int:visit_id>/', views_doctor.visit_detail, name='visit_detail'),
    path('doctor/visit/<int:visit_id>/notes/new/', views_doctor.clinical_note_create, name='clinical_note_create'),
    path('doctor/visit/<int:visit_id>/diagnosis/new/', views_doctor.diagnosis_create, name='diagnosis_create'),
    path('doctor/visit/<int:visit_id>/lab/order/', views_doctor.lab_order_multi_create, name='lab_order_multi_create'),
    path('doctor/visit/<int:visit_id>/imaging/new/', views_doctor.imaging_order_create, name='imaging_order_create'),
    path('doctor/visit/<int:visit_id>/medication/new/', views_doctor.medication_order_create, name='medication_order_create'),
    path('doctor/visit/<int:visit_id>/medication/<int:order_id>/discontinue/', views_doctor.medication_order_discontinue, name='medication_order_discontinue'),
    path('doctor/visit/<int:visit_id>/procedure/new/', views_doctor.procedure_order_create, name='procedure_order_create'),
    path('doctor/visit/<int:visit_id>/vitals/new/', views_doctor.vital_sign_create, name='vital_sign_create'),
    path('doctor/patient/<int:patient_id>/history/', views_doctor.patient_history, name='patient_history'),

    # ── Patient Attachment & Document Management ───────────────────────────────
    path('patients/<int:patient_id>/attachments/', views_attachments.patient_attachment_list, name='patient_attachment_list'),
    path('patients/<int:patient_id>/attachments/upload/', views_attachments.patient_attachment_upload, name='patient_attachment_upload'),
    path('patients/<int:patient_id>/attachments/deleted/', views_attachments.patient_attachment_deleted_list, name='patient_attachment_deleted_list'),
    path('attachments/<int:attachment_id>/replace/', views_attachments.patient_attachment_replace, name='patient_attachment_replace'),
    path('attachments/<int:attachment_id>/versions/', views_attachments.attachment_version_history, name='attachment_version_history'),
    path('attachments/<int:attachment_id>/preview/', views_attachments.patient_attachment_preview, name='patient_attachment_preview'),
    path('attachments/<int:attachment_id>/download/', views_attachments.patient_attachment_download, name='patient_attachment_download'),
    path('attachments/<int:attachment_id>/delete/', views_attachments.patient_attachment_delete, name='patient_attachment_delete'),
    path('attachments/<int:attachment_id>/restore/', views_attachments.patient_attachment_restore, name='patient_attachment_restore'),
    path('attachments/<int:attachment_id>/comment/', views_attachments.attachment_comment_add, name='attachment_comment_add'),
    path('attachment-categories/', views_attachments.attachment_category_list, name='attachment_category_list'),
    path('attachment-categories/new/', views_attachments.attachment_category_create, name='attachment_category_create'),
    path('attachment-categories/<int:category_id>/edit/', views_attachments.attachment_category_edit, name='attachment_category_edit'),
    path('doctor/visit/<int:visit_id>/schedule-followup/', views_doctor.schedule_followup, name='schedule_followup'),

    # ── Electronic Prescriptions (Doctor side) ──────────────────────────────
    path('prescriptions/visit/<int:visit_id>/new/', views_prescription.prescription_create, name='prescription_create'),
    path('prescriptions/<int:rx_id>/', views_prescription.prescription_detail, name='prescription_detail'),
    path('prescriptions/<int:rx_id>/send/', views_prescription.prescription_send, name='prescription_send'),
    path('prescriptions/<int:rx_id>/cancel/', views_prescription.prescription_cancel, name='prescription_cancel'),
    path('prescriptions/patient/<int:patient_id>/history/', views_prescription.prescription_history, name='prescription_history'),
    path('prescriptions/api/search/', views_prescription.medication_search_api, name='medication_search_api'),
    path('prescriptions/visit/<int:visit_id>/mar/', views_prescription.mar_list, name='mar_list'),
    path('prescriptions/mar/<int:entry_id>/update/', views_prescription.mar_update, name='mar_update'),

    # ── Electronic Prescriptions (Pharmacy side) ────────────────────────────
    path('pharmacy/rx/', views_prescription.rx_queue, name='rx_queue'),
    path('pharmacy/rx/<int:rx_id>/', views_prescription.rx_detail, name='rx_detail'),
    path('pharmacy/rx/<int:rx_id>/verify/', views_prescription.rx_verify, name='rx_verify'),
    path('pharmacy/rx/<int:rx_id>/dispense/', views_prescription.rx_dispense, name='rx_dispense'),
    path('pharmacy/rx/<int:rx_id>/print/', views_prescription.rx_print, name='rx_print'),
    path('pharmacy/rx/<int:rx_id>/confirm-dispense/', views_prescription.rx_confirm_dispense, name='rx_confirm_dispense'),
    path('pharmacy/rx/<int:rx_id>/credit-approve/', views_prescription.rx_credit_approve, name='rx_credit_approve'),
    path('pharmacy/rx/<int:rx_id>/credit-revoke/', views_prescription.rx_credit_revoke, name='rx_credit_revoke'),
    path('pharmacy/reports/revenue/', views_prescription.report_medication_revenue, name='report_medication_revenue'),
    path('pharmacy/reports/payments/', views_prescription.report_medication_payments, name='report_medication_payments'),
    path('pharmacy/reports/patient-medication/', views_prescription.report_patient_medication, name='report_patient_medication'),
    path('pharmacy/reports/outstanding/', views_prescription.report_pharmacy_outstanding, name='report_pharmacy_outstanding'),

    # ── Queue & Triage module ─────────────────────────────────────────────────
    path('queue/', views_queue.queue_dashboard, name='queue_dashboard'),
    path('queue/call-next/', views_queue.queue_call_next, name='queue_call_next'),
    path('queue/<int:queue_id>/update-status/', views_queue.queue_update_status, name='queue_update_status'),
    path('triage/', views_queue.triage_dashboard, name='triage_dashboard'),
    path('triage/<int:visit_id>/assess/', views_queue.triage_create, name='triage_create'),

    # ── Laboratory module ────────────────────────────────────────────────────
    path('lab/', views_lab.lab_dashboard, name='lab_dashboard'),
    path('lab/order/<int:order_id>/', views_lab.lab_order_detail, name='lab_order_detail'),
    path('lab/order/<int:order_id>/result/', views_lab.lab_result_enter, name='lab_result_enter'),
    path('lab/order/<int:order_id>/print/', views_lab.lab_order_print, name='lab_order_print'),
    path('lab/order/<int:order_id>/release/', views_lab.lab_result_release, name='lab_result_release'),
    path('lab/order/<int:order_id>/status/', views_lab.lab_order_update_status, name='lab_order_update_status'),
    path('lab/order/<int:order_id>/sample/', views_lab.lab_sample_collect, name='lab_sample_collect'),
    path('lab/order/<int:order_id>/cancel/', views_lab.lab_order_cancel, name='lab_order_cancel'),
    path('lab/order/<int:order_id>/consumable/', views_lab.lab_consumable_use, name='lab_consumable_use'),
    path('lab/services/', views_lab.lab_service_list, name='lab_service_list'),
    path('lab/services/new/', views_lab.lab_service_create, name='lab_service_create'),
    path('lab/services/<int:pk>/', views_lab.lab_service_detail, name='lab_service_detail'),
    path('lab/services/<int:pk>/edit/', views_lab.lab_service_edit, name='lab_service_edit'),
    path('lab/services/<int:pk>/toggle/', views_lab.lab_service_toggle, name='lab_service_toggle'),
    path('lab/categories/', views_lab.lab_category_list, name='lab_category_list'),
    path('lab/categories/new/', views_lab.lab_category_create, name='lab_category_create'),
    path('lab/categories/<int:pk>/edit/', views_lab.lab_category_edit, name='lab_category_edit'),
    path('lab/groups/', views_lab.lab_test_group_list, name='lab_test_group_list'),
    path('lab/groups/new/', views_lab.lab_test_group_create, name='lab_test_group_create'),
    path('lab/groups/<int:pk>/edit/', views_lab.lab_test_group_edit, name='lab_test_group_edit'),
    path('lab/services/<int:service_id>/ranges/new/', views_lab.lab_reference_range_create, name='lab_reference_range_create'),
    path('lab/services/<int:service_id>/ranges/<int:pk>/edit/', views_lab.lab_reference_range_edit, name='lab_reference_range_edit'),
    path('lab/services/<int:service_id>/ranges/<int:pk>/delete/', views_lab.lab_reference_range_delete, name='lab_reference_range_delete'),
    path('lab/api/search/', views_lab.lab_service_search_api, name='lab_service_search_api'),
    path('lab/reports/usage/', views_lab.report_lab_usage, name='report_lab_usage'),
    path('lab/reports/prices/', views_lab.report_lab_prices, name='report_lab_prices'),
    path('lab/reports/new-tests/', views_lab.report_lab_new_tests, name='report_lab_new_tests'),
    path('lab/reports/inventory/', views_lab.report_lab_inventory, name='report_lab_inventory'),
    path('lab/reports/master-list/', views_lab.report_lab_master_list, name='report_lab_master_list'),
    path('lab/reports/by-category/', views_lab.report_lab_by_category, name='report_lab_by_category'),
    path('lab/reports/by-department/', views_lab.report_lab_by_department, name='report_lab_by_department'),
    path('lab/reports/tat/', views_lab.report_lab_tat, name='report_lab_tat'),
    path('lab/reports/critical/', views_lab.report_lab_critical, name='report_lab_critical'),

    # ── Radiology module ─────────────────────────────────────────────────────
    path('radiology/', views_radiology.radiology_dashboard, name='radiology_dashboard'),
    path('radiology/order/<int:order_id>/', views_radiology.imaging_order_detail, name='imaging_order_detail'),
    path('radiology/order/<int:order_id>/report/', views_radiology.imaging_report_enter, name='imaging_report_enter'),
    path('radiology/order/<int:order_id>/status/', views_radiology.imaging_order_update_status, name='imaging_order_update_status'),
    path('radiology/services/', views_radiology.imaging_service_list, name='imaging_service_list'),
    path('radiology/services/new/', views_radiology.imaging_service_create, name='imaging_service_create'),
    path('radiology/services/<int:pk>/', views_radiology.imaging_service_detail, name='imaging_service_detail'),
    path('radiology/services/<int:pk>/edit/', views_radiology.imaging_service_edit, name='imaging_service_edit'),
    path('radiology/services/<int:pk>/toggle/', views_radiology.imaging_service_toggle, name='imaging_service_toggle'),
    path('radiology/api/search/', views_radiology.imaging_service_search_api, name='imaging_service_search_api'),

    # ── Pharmacy module ──────────────────────────────────────────────────────
    path('pharmacy/', views_pharmacy.pharmacy_dashboard, name='pharmacy_dashboard'),
    path('pharmacy/stock/', views_pharmacy.pharmacy_stock_list, name='pharmacy_stock_list'),
    path('pharmacy/stock/new/', views_pharmacy.pharmacy_stock_create, name='pharmacy_stock_create'),
    path('pharmacy/stock/<int:stock_id>/edit/', views_pharmacy.pharmacy_stock_edit, name='pharmacy_stock_edit'),
    path('pharmacy/stock/<int:stock_id>/adjust/', views_pharmacy.pharmacy_stock_adjust, name='pharmacy_stock_adjust'),
    path('pharmacy/api/search/', views_pharmacy.pharmacy_stock_search_api, name='pharmacy_stock_search_api'),
    path('pharmacy/prescriptions/', views_pharmacy.pharmacy_prescriptions, name='pharmacy_prescriptions'),
    path('pharmacy/dispense/<int:order_id>/', views_pharmacy.pharmacy_dispense, name='pharmacy_dispense'),
    path('pharmacy/sales/', views_pharmacy.pharmacy_sales, name='pharmacy_sales'),

    # ── Pharmacy POS ────────────────────────────────────────────────────────────
    path('pharmacy/pos/', views_pharmacy_pos.pharmacy_pos, name='pharmacy_pos'),
    path('pharmacy/pos/create/', views_pharmacy_pos.pharmacy_sale_create, name='pharmacy_sale_create'),
    path('pharmacy/pos/search/product/', views_pharmacy_pos.pharmacy_product_search, name='pharmacy_product_search'),
    path('pharmacy/pos/search/patient/', views_pharmacy_pos.pharmacy_patient_search, name='pharmacy_patient_search'),
    path('pharmacy/pos/sales/', views_pharmacy_pos.pharmacy_sales_list, name='pharmacy_sales_list'),
    path('pharmacy/pos/sales/<int:sale_id>/', views_pharmacy_pos.pharmacy_sale_detail, name='pharmacy_sale_detail'),
    path('pharmacy/pos/sales/<int:sale_id>/receipt/', views_pharmacy_pos.pharmacy_sale_receipt, name='pharmacy_sale_receipt'),
    path('pharmacy/pos/sales/<int:sale_id>/dispense/', views_pharmacy_pos.pharmacy_sale_dispense, name='pharmacy_sale_dispense'),
    path('pharmacy/pos/sales/<int:sale_id>/cancel/', views_pharmacy_pos.pharmacy_sale_cancel, name='pharmacy_sale_cancel'),
    path('pharmacy/pos/sales/<int:sale_id>/return/', views_pharmacy_pos.pharmacy_return_create, name='pharmacy_return_create'),
    path('pharmacy/pos/returns/<int:return_id>/', views_pharmacy_pos.pharmacy_return_detail, name='pharmacy_return_detail'),
    path('pharmacy/pos/returns/<int:return_id>/approve/', views_pharmacy_pos.pharmacy_return_approve, name='pharmacy_return_approve'),
    # Reports
    path('pharmacy/reports/daily/', views_pharmacy_pos.pharmacy_report_daily, name='pharmacy_report_daily'),
    path('pharmacy/reports/medications/', views_pharmacy_pos.pharmacy_report_medications, name='pharmacy_report_medications'),
    path('pharmacy/reports/credit/', views_pharmacy_pos.pharmacy_report_credit, name='pharmacy_report_credit'),

    # ── Inventory module ─────────────────────────────────────────────────────
    path('inventory/', views_inventory.inventory_dashboard, name='inventory_dashboard'),
    path('inventory/items/', views_inventory.inventory_item_list, name='inventory_item_list'),
    path('inventory/items/new/', views_inventory.inventory_item_create, name='inventory_item_create'),
    path('inventory/items/<int:item_id>/edit/', views_inventory.inventory_item_edit, name='inventory_item_edit'),
    path('inventory/items/<int:item_id>/adjust/', views_inventory.inventory_item_adjust, name='inventory_item_adjust'),
    path('inventory/item-groups/', views_inventory.item_group_list, name='item_group_list'),
    path('inventory/item-groups/new/', views_inventory.item_group_create, name='item_group_create'),
    path('inventory/item-groups/<int:group_id>/edit/', views_inventory.item_group_edit, name='item_group_edit'),
    path('inventory/units/', views_inventory.unit_of_measure_list, name='unit_of_measure_list'),
    path('inventory/units/new/', views_inventory.unit_of_measure_create, name='unit_of_measure_create'),
    path('inventory/units/<int:unit_id>/toggle/', views_inventory.unit_of_measure_toggle, name='unit_of_measure_toggle'),
    path('inventory/purchase-orders/', views_inventory.purchase_order_list, name='purchase_order_list'),
    path('inventory/purchase-orders/new/', views_inventory.purchase_order_create, name='purchase_order_create'),
    path('inventory/purchase-orders/<int:po_id>/', views_inventory.purchase_order_detail, name='purchase_order_detail'),
    path('inventory/purchase-orders/<int:po_id>/add-item/', views_inventory.purchase_order_add_item, name='purchase_order_add_item'),
    path('inventory/purchase-orders/<int:po_id>/status/', views_inventory.purchase_order_update_status, name='purchase_order_update_status'),
    path('inventory/reports/purchase-report/', views_inventory.report_purchase_orders, name='report_purchase_orders'),
    path('inventory/reports/item-master/', views_inventory.report_inventory_item_master, name='report_inventory_item_master'),

    # ── Enhanced Store: item detail, batches, transactions, equipment ─────────
    path('inventory/items/<int:pk>/', views_store.store_item_detail, name='store_item_detail'),
    path('inventory/items/<int:pk>/deactivate/', views_store.store_item_deactivate, name='store_item_deactivate'),
    path('inventory/items/<int:item_pk>/receive-batch/', views_store.store_batch_receive, name='store_batch_receive'),
    path('inventory/items/<int:item_pk>/issue/', views_store.store_issue_item, name='store_issue_item'),
    path('inventory/items/<int:item_pk>/manual-adjust/', views_store.store_item_adjust, name='store_item_adjust'),
    path('inventory/batches/', views_store.store_batch_list, name='store_batch_list'),
    path('inventory/batches/<int:pk>/dispose/', views_store.store_batch_dispose, name='store_batch_dispose'),
    path('inventory/transactions/', views_store.store_transaction_list, name='store_transaction_list'),

    # ── Equipment / Assets ─────────────────────────────────────────────────────
    path('inventory/equipment/', views_store.equipment_list, name='equipment_list'),
    path('inventory/equipment/new/', views_store.equipment_create, name='equipment_create'),
    path('inventory/equipment/<int:pk>/', views_store.equipment_detail, name='equipment_detail'),
    path('inventory/equipment/<int:pk>/edit/', views_store.equipment_edit, name='equipment_edit'),
    path('inventory/equipment/<int:asset_pk>/maintenance/', views_store.equipment_maintenance_add, name='equipment_maintenance_add'),

    # ── Purchase Requests ─────────────────────────────────────────────────────
    path('inventory/purchase-requests/', views_store.purchase_request_list, name='purchase_request_list'),
    path('inventory/purchase-requests/new/', views_store.purchase_request_create, name='purchase_request_create'),
    path('inventory/purchase-requests/<int:pk>/', views_store.purchase_request_detail, name='purchase_request_detail'),
    path('inventory/purchase-requests/<int:pk>/approve/', views_store.purchase_request_approve, name='purchase_request_approve'),
    path('inventory/purchase-requests/<int:pk>/convert/', views_store.purchase_request_convert, name='purchase_request_convert'),

    # ── Physical Stock Count ──────────────────────────────────────────────────
    path('inventory/stock-counts/', views_store.stock_count_list, name='stock_count_list'),
    path('inventory/stock-counts/new/', views_store.stock_count_create, name='stock_count_create'),
    path('inventory/stock-counts/<int:pk>/', views_store.stock_count_detail, name='stock_count_detail'),
    path('inventory/stock-counts/<int:pk>/enter/', views_store.stock_count_enter, name='stock_count_enter'),
    path('inventory/stock-counts/<int:pk>/approve/', views_store.stock_count_approve, name='stock_count_approve'),

    # ── Physical Inventory Count & Inventory Period Management ────────────────
    path('inventory/periods/', views_physical_count.inventory_period_list, name='inventory_period_list'),
    path('inventory/periods/new/', views_physical_count.inventory_period_create, name='inventory_period_create'),
    path('inventory/periods/<int:pk>/', views_physical_count.inventory_period_detail, name='inventory_period_detail'),
    path('inventory/periods/<int:pk>/close/', views_physical_count.inventory_period_close, name='inventory_period_close'),
    path('inventory/physical-counts/', views_physical_count.physical_count_list, name='physical_count_list'),
    path('inventory/physical-counts/new/', views_physical_count.physical_count_create, name='physical_count_create'),
    path('inventory/physical-counts/<int:pk>/', views_physical_count.physical_count_detail, name='physical_count_detail'),
    path('inventory/physical-counts/<int:pk>/enter/', views_physical_count.physical_count_enter, name='physical_count_enter'),
    path('inventory/physical-counts/<int:pk>/approve/', views_physical_count.physical_count_approve, name='physical_count_approve'),

    # ── Store Reports ────────────────────────────────────────────────────────
    path('inventory/reports/stock-on-hand/', views_store.report_store_stock_on_hand, name='report_store_stock_on_hand'),
    path('inventory/reports/low-stock/', views_store.report_store_low_stock, name='report_store_low_stock'),
    path('inventory/reports/expiry/', views_store.report_store_expiry, name='report_store_expiry'),
    path('inventory/reports/valuation/', views_store.report_store_valuation, name='report_store_valuation'),
    path('inventory/reports/transactions/', views_store.report_store_transactions, name='report_store_transactions'),
    path('inventory/reports/out-of-stock/', views_store.report_store_out_of_stock, name='report_store_out_of_stock'),
    path('inventory/reports/damaged/', views_store.report_store_damaged, name='report_store_damaged'),
    path('inventory/reports/goods-receiving/', views_store.report_store_goods_receiving, name='report_store_goods_receiving'),
    path('inventory/reports/goods-issue/', views_store.report_store_goods_issue, name='report_store_goods_issue'),
    path('inventory/reports/adjustments/', views_store.report_store_adjustments, name='report_store_adjustments'),
    path('inventory/reports/equipment/', views_store.report_store_equipment, name='report_store_equipment'),

    # ── Human Resources module ────────────────────────────────────────────────
    path('hr/', views_hr.hr_dashboard, name='hr_dashboard'),
    path('hr/employees/', views_hr.employee_list, name='employee_list'),
    path('hr/employees/new/', views_hr.employee_create, name='employee_create'),
    path('hr/employees/<int:employee_id>/', views_hr.employee_detail, name='employee_detail'),
    path('hr/employees/<int:employee_id>/edit/', views_hr.employee_edit, name='employee_edit'),
    path('hr/employees/<int:employee_id>/signature/upload/', views_signatures.employee_signature_upload, name='employee_signature_upload'),
    path('hr/employees/<int:employee_id>/signature/remove/', views_signatures.employee_signature_remove, name='employee_signature_remove'),
    path('hr/employees/<int:employee_id>/signature/image/', views_signatures.employee_signature_image, name='employee_signature_image'),
    path('hr/attendance/', views_hr.attendance_list, name='attendance_list'),
    path('hr/attendance/mark/', views_hr.attendance_mark, name='attendance_mark'),
    path('hr/leave/', views_hr.leave_request_list, name='leave_request_list'),
    path('hr/leave/new/', views_hr.leave_request_create, name='leave_request_create'),
    path('hr/leave/<int:request_id>/review/', views_hr.leave_request_review, name='leave_request_review'),

    # ── Anesthesia module ─────────────────────────────────────────────────────
    path('anesthesia/', views_anesthesia.anesthesia_dashboard, name='anesthesia_dashboard'),
    path('anesthesia/records/', views_anesthesia.anesthesia_record_list, name='anesthesia_record_list'),
    path('anesthesia/visit/<int:visit_id>/new/', views_anesthesia.anesthesia_record_create, name='anesthesia_record_create'),
    path('anesthesia/record/<int:record_id>/', views_anesthesia.anesthesia_record_detail, name='anesthesia_record_detail'),
    path('anesthesia/record/<int:record_id>/edit/', views_anesthesia.anesthesia_record_edit, name='anesthesia_record_edit'),

    # ── Billing module ────────────────────────────────────────────────────────
    path('billing/', views_billing.billing_dashboard, name='billing_dashboard'),
    path('billing/settings/service-charge/', views_billing.service_charge_settings_edit, name='service_charge_settings_edit'),
    path('billing/invoices/', views_billing.invoice_list, name='invoice_list'),
    path('billing/split/', views_billing.invoice_split_view, name='invoice_split_view'),
    path('billing/panels/paid/', views_billing.invoice_panel_paid, name='invoice_panel_paid'),
    path('billing/panels/unpaid/', views_billing.invoice_panel_unpaid, name='invoice_panel_unpaid'),
    path('billing/invoices/new/', views_billing.invoice_create, name='invoice_create'),
    path('billing/invoices/<int:invoice_id>/', views_billing.invoice_detail, name='invoice_detail'),
    path('billing/invoices/<int:invoice_id>/add-item/', views_billing.invoice_add_item, name='invoice_add_item'),
    path('billing/items/<int:item_id>/delete/', views_billing.invoice_delete_item, name='invoice_delete_item'),
    path('billing/items/<int:item_id>/credit-approve/', views_billing.invoice_item_credit_approve, name='invoice_item_credit_approve'),
    path('billing/items/<int:item_id>/cancel/', views_billing.invoice_item_cancel, name='invoice_item_cancel'),
    path('billing/items/<int:item_id>/refund/', views_billing.invoice_item_refund, name='invoice_item_refund'),
    path('billing/invoices/<int:invoice_id>/status/', views_billing.invoice_update_status, name='invoice_update_status'),
    path('billing/invoices/<int:invoice_id>/payment/', views_billing.payment_create, name='payment_create'),
    path('billing/invoices/<int:invoice_id>/payment/<int:payment_id>/receipt/', views_billing.invoice_receipt, name='invoice_receipt'),
    path('billing/invoices/<int:invoice_id>/discount/', views_billing.invoice_apply_discount, name='invoice_apply_discount'),
    # Credit
    path('billing/invoices/<int:invoice_id>/credit/', views_billing.credit_invoice_create, name='credit_invoice_create'),
    path('billing/invoices/<int:invoice_id>/credit/approve/', views_billing.credit_approve, name='credit_approve'),
    path('billing/credit/', views_billing.credit_list, name='credit_list'),
    # Cash sessions
    path('billing/cash-sessions/', views_billing.cash_session_list, name='cash_session_list'),
    path('billing/cash-sessions/open/', views_billing.cash_session_open, name='cash_session_open'),
    path('billing/cash-sessions/<int:session_id>/close/', views_billing.cash_session_close, name='cash_session_close'),
    # Reports
    path('billing/reports/cash/', views_billing.report_cash_collection, name='report_cash_collection'),
    path('billing/reports/credit/', views_billing.report_credit, name='report_credit'),
    path('billing/reports/outstanding/', views_billing.report_outstanding, name='report_outstanding'),

    # ── Receptionist / Front Desk module ─────────────────────────────────────
    path('receptionist/', views_receptionist.receptionist_dashboard, name='receptionist_dashboard'),
    path('receptionist/appointments/', views_receptionist.appointment_list, name='appointment_list'),
    path('receptionist/appointments/new/', views_receptionist.appointment_create, name='appointment_create'),
    path('receptionist/appointments/new/walk-in/', views_receptionist.appointment_create_walkin, name='appointment_create_walkin'),
    path('receptionist/appointments/<int:appt_id>/register/', views_receptionist.register_patient_for_appointment, name='register_patient_for_appointment'),
    path('receptionist/appointments/<int:appt_id>/', views_receptionist.appointment_detail, name='appointment_detail'),
    path('receptionist/appointments/<int:appt_id>/edit/', views_receptionist.appointment_edit, name='appointment_edit'),
    path('receptionist/appointments/<int:appt_id>/start-visit/', views_receptionist.appointment_start_visit, name='appointment_start_visit'),
    path('receptionist/appointments/<int:appt_id>/confirm/', views_receptionist.appointment_confirm, name='appointment_confirm'),
    path('receptionist/appointments/<int:appt_id>/cancel/', views_receptionist.appointment_cancel, name='appointment_cancel'),
    path('receptionist/appointments/<int:appt_id>/mark-arrived/', views_receptionist.appointment_mark_arrived, name='appointment_mark_arrived'),
    path('receptionist/appointments/<int:appt_id>/checkin-summary/', views_receptionist.appointment_checkin_summary, name='appointment_checkin_summary'),
    path('receptionist/doctor-schedules/', views_receptionist.doctor_schedule_view, name='doctor_schedule_view'),
    path('receptionist/doctor-schedules/<int:doctor_id>/edit/', views_receptionist.doctor_schedule_edit, name='doctor_schedule_edit'),
    path('receptionist/api/doctor-availability/', views_receptionist.doctor_availability_api, name='doctor_availability_api'),
    path('receptionist/patient-flow/', views_receptionist.patient_flow, name='patient_flow'),

    # ── Consultation Appointment Scheduling ──────────────────────────────────
    path('appointments/', views_appointments.consultation_dashboard, name='consultation_dashboard'),
    path('appointments/list/', views_appointments.appt_list, name='appt_list'),
    path('appointments/new/', views_appointments.appt_create, name='appt_create'),
    path('appointments/api/patient-search/', views_appointments.appt_patient_search, name='appt_patient_search'),
    path('appointments/<int:pk>/', views_appointments.appt_detail, name='appt_detail'),
    path('appointments/<int:pk>/edit/', views_appointments.appt_edit, name='appt_edit'),
    path('appointments/<int:pk>/cancel/', views_appointments.appt_cancel, name='appt_cancel'),
    path('appointments/<int:pk>/reschedule/', views_appointments.appt_reschedule, name='appt_reschedule'),
    path('appointments/<int:pk>/no-show/', views_appointments.appt_no_show, name='appt_no_show'),
    path('appointments/<int:pk>/slip/', views_appointments.appt_slip, name='appt_slip'),
    path('appointments/doctor-availability/', views_appointments.doctor_availability_list, name='doctor_availability_list'),
    path('appointments/doctor-availability/<int:doctor_id>/edit/', views_appointments.doctor_availability_edit, name='doctor_availability_edit'),
    path('appointments/doctor-availability/<int:doctor_id>/exceptions/', views_appointments.doctor_availability_exception, name='doctor_availability_exception'),
    path('appointments/api/slots/', views_appointments.get_doctor_slots, name='get_doctor_slots'),
    path('appointments/reports/daily-schedule/', views_appointments.report_appt_daily_schedule, name='report_appt_daily_schedule'),
    path('appointments/reports/dept-schedule/', views_appointments.report_appt_dept_schedule, name='report_appt_dept_schedule'),
    path('appointments/reports/list/', views_appointments.report_appt_list, name='report_appt_list'),
    path('appointments/reports/cancelled/', views_appointments.report_appt_cancelled, name='report_appt_cancelled'),
    path('appointments/reports/no-show/', views_appointments.report_appt_no_show, name='report_appt_no_show'),
    path('appointments/reports/workload/', views_appointments.report_appt_workload, name='report_appt_workload'),

    # ── Medication Inventory module ───────────────────────────────────────────
    path('med-inventory/', views_med_inventory.med_inventory_dashboard, name='med_inventory_dashboard'),
    path('med-inventory/medications/', views_med_inventory.medication_list, name='medication_list'),
    path('med-inventory/medications/new/', views_med_inventory.medication_create, name='medication_create'),
    path('med-inventory/medications/<int:med_id>/', views_med_inventory.medication_detail, name='medication_detail'),
    path('med-inventory/medications/<int:med_id>/edit/', views_med_inventory.medication_edit, name='medication_edit'),
    path('med-inventory/medications/<int:med_id>/deactivate/', views_med_inventory.medication_deactivate, name='medication_deactivate'),
    path('med-inventory/batches/', views_med_inventory.batch_list, name='batch_list'),
    path('med-inventory/receive/', views_med_inventory.batch_receive_select, name='batch_receive_select'),
    path('med-inventory/medications/<int:med_id>/receive/', views_med_inventory.batch_receive, name='batch_receive'),
    path('med-inventory/batches/<int:batch_id>/dispose/', views_med_inventory.batch_dispose, name='batch_dispose'),
    path('med-inventory/adjustment/', views_med_inventory.stock_adjustment, name='stock_adjustment'),
    path('med-inventory/suppliers/', views_med_inventory.supplier_list, name='supplier_list'),
    path('med-inventory/suppliers/new/', views_med_inventory.supplier_create, name='supplier_create'),
    path('med-inventory/suppliers/<int:supplier_id>/edit/', views_med_inventory.supplier_edit, name='supplier_edit'),
    path('med-inventory/reports/suppliers/', views_med_inventory.report_supplier_performance, name='report_supplier_performance'),
    path('med-inventory/transactions/', views_med_inventory.transaction_list, name='transaction_list'),
    path('med-inventory/reports/stock-on-hand/', views_med_inventory.report_stock_on_hand, name='report_stock_on_hand'),
    path('med-inventory/reports/expiry/', views_med_inventory.report_expiry, name='report_expiry'),
    path('med-inventory/reports/stock-movement/', views_med_inventory.report_stock_movement, name='report_stock_movement'),
    path('med-inventory/reports/low-stock/', views_med_inventory.report_low_stock, name='report_low_stock'),
    path('med-inventory/reports/stock-card/', views_med_inventory.report_stock_card, name='report_stock_card'),
    path('med-inventory/reports/valuation/', views_med_inventory.report_valuation, name='report_valuation'),

    # ── Department Pharmacy module ────────────────────────────────────────────
    path('dept-pharmacy/', views_dept_pharmacy.dept_pharmacy_dashboard, name='dept_pharmacy_dashboard'),

    # Stores
    path('dept-pharmacy/stores/', views_dept_pharmacy.dept_store_list, name='dept_store_list'),
    path('dept-pharmacy/stores/new/', views_dept_pharmacy.dept_store_create, name='dept_store_create'),
    path('dept-pharmacy/stores/<int:store_id>/', views_dept_pharmacy.dept_store_detail, name='dept_store_detail'),
    path('dept-pharmacy/stores/<int:store_id>/edit/', views_dept_pharmacy.dept_store_edit, name='dept_store_edit'),

    # Transfer Requests
    path('dept-pharmacy/requests/', views_dept_pharmacy.transfer_request_list, name='transfer_request_list'),
    path('dept-pharmacy/requests/new/', views_dept_pharmacy.transfer_request_create, name='transfer_request_create'),
    path('dept-pharmacy/requests/<int:req_id>/', views_dept_pharmacy.transfer_request_detail, name='transfer_request_detail'),
    path('dept-pharmacy/requests/<int:req_id>/ward-approve/', views_dept_pharmacy.transfer_request_ward_approve, name='transfer_request_ward_approve'),
    path('dept-pharmacy/requests/<int:req_id>/approve/', views_dept_pharmacy.transfer_request_approve, name='transfer_request_approve'),
    path('dept-pharmacy/requests/<int:req_id>/fulfill/', views_dept_pharmacy.transfer_request_fulfill, name='transfer_request_fulfill'),

    # Transfers
    path('dept-pharmacy/transfers/', views_dept_pharmacy.dept_transfer_list, name='dept_transfer_list'),
    path('dept-pharmacy/transfers/<int:transfer_id>/', views_dept_pharmacy.dept_transfer_detail, name='dept_transfer_detail'),
    path('dept-pharmacy/transfers/<int:transfer_id>/receive/', views_dept_pharmacy.dept_transfer_receive, name='dept_transfer_receive'),

    # Returns
    path('dept-pharmacy/stores/<int:store_id>/return/', views_dept_pharmacy.dept_return_create, name='dept_return_create'),

    # Usage
    path('dept-pharmacy/usage/', views_dept_pharmacy.dept_usage_list, name='dept_usage_list'),
    path('dept-pharmacy/stores/<int:store_id>/usage/new/', views_dept_pharmacy.dept_usage_create, name='dept_usage_create'),

    # Reports
    path('dept-pharmacy/reports/stock-on-hand/', views_dept_pharmacy.report_dept_stock_on_hand, name='dept_report_stock_on_hand'),
    path('dept-pharmacy/reports/stock-card/', views_dept_pharmacy.report_dept_stock_card, name='dept_report_stock_card'),
    path('dept-pharmacy/reports/consumption/', views_dept_pharmacy.report_dept_consumption, name='dept_report_consumption'),
    path('dept-pharmacy/reports/transfers/', views_dept_pharmacy.report_transfer_history, name='dept_report_transfer_history'),

    # ── Reports & Analytics module ────────────────────────────────────────────
    path('reports/', views_reports.reports_hub, name='reports_hub'),
    path('reports/', views_reports.reports_hub, name='reports_dashboard'),  # backward compat

    # Management reports
    path('reports/executive/', views_reports.report_executive, name='report_executive'),
    path('reports/revenue/', views_reports.report_revenue, name='report_revenue'),
    path('reports/invoice-status/', views_reports.report_invoice_status, name='report_invoice_status'),

    # Patient reports
    path('reports/patients/registration/', views_reports.report_patient_registration, name='report_patient_registration'),
    path('reports/patients/visits/', views_reports.report_patient_visits, name='report_patient_visits'),
    path('reports/patients/', views_reports.report_patients, name='report_patients'),

    # Clinical reports
    path('reports/clinical/doctor-performance/', views_reports.report_doctor_performance, name='report_doctor_performance'),
    path('reports/clinical/diagnosis/', views_reports.report_diagnosis, name='report_diagnosis'),
    path('reports/clinical/lab/', views_reports.report_lab_activity, name='report_lab_activity'),
    path('reports/clinical/radiology/', views_reports.report_radiology_activity, name='report_radiology_activity'),
    path('reports/clinical/', views_reports.report_clinical, name='report_clinical'),

    # Pharmacy reports
    path('reports/pharmacy/summary/', views_reports.report_pharmacy_summary, name='report_pharmacy_summary'),
    path('reports/pharmacy/prescriptions/', views_reports.report_prescriptions, name='report_prescriptions'),

    # Finance/staff
    path('reports/financial/', views_reports.report_financial, name='report_financial'),
    path('reports/staff/', views_reports.report_staff, name='report_staff'),
    path('reports/hr/employees/', views_reports.report_employees, name='report_employees'),
    path('reports/audit/activity/', views_reports.report_audit_activity, name='report_audit_activity'),

    # ── Facility Management Reports ──────────────────────────────────────────
    path('reports/facility/bed-occupancy/', views_reports.report_bed_occupancy, name='report_bed_occupancy'),
    path('reports/facility/ward-occupancy/', views_reports.report_ward_occupancy, name='report_ward_occupancy'),
    path('reports/facility/room-utilization/', views_reports.report_room_utilization, name='report_room_utilization'),
    path('reports/facility/or-utilization/', views_reports.report_or_utilization, name='report_or_utilization'),
    path('reports/facility/admission-discharge/', views_reports.report_admission_discharge, name='report_admission_discharge'),
    path('reports/facility/patient-transfer/', views_reports.report_patient_transfer, name='report_patient_transfer'),
    path('reports/facility/maintenance/', views_reports.report_facility_maintenance, name='report_facility_maintenance'),

    path('reports/admissions/register/', views_reports.report_admission_register, name='report_admission_register'),
    path('reports/admissions/daily/', views_reports.report_daily_admissions, name='report_daily_admissions'),
    path('reports/admissions/length-of-stay/', views_reports.report_length_of_stay, name='report_length_of_stay'),
    path('reports/admissions/deposit-collection/', views_reports.report_deposit_collection, name='report_deposit_collection'),
    path('reports/admissions/revenue/', views_reports.report_admission_revenue, name='report_admission_revenue'),
    path('reports/admissions/department-stats/', views_reports.report_department_admission_stats, name='report_department_admission_stats'),
    path('reports/admissions/readmissions/', views_reports.report_readmissions, name='report_readmissions'),
    path('reports/admissions/cancellations/', views_reports.report_admission_cancellations, name='report_admission_cancellations'),

    path('reports/attachments/history/', views_reports.report_attachment_history, name='report_attachment_history'),
    path('reports/attachments/by-category/', views_reports.report_attachments_by_category, name='report_attachments_by_category'),
    path('reports/attachments/by-department/', views_reports.report_attachments_by_department, name='report_attachments_by_department'),
    path('reports/attachments/missing-required/', views_reports.report_missing_required_documents, name='report_missing_required_documents'),
    path('reports/attachments/recent/', views_reports.report_recent_attachments, name='report_recent_attachments'),
    path('reports/attachments/confidential/', views_reports.report_confidential_attachments, name='report_confidential_attachments'),
    path('reports/attachments/activity-log/', views_reports.report_attachment_activity_log, name='report_attachment_activity_log'),
    path('reports/facility/available-beds/', views_reports.report_available_beds, name='report_available_beds'),
    path('reports/facility/room-status/', views_reports.report_room_status, name='report_room_status'),

    # ── Card & Consultation Type Reports ──────────────────────────────────────
    path('reports/cards/card-type-usage/', views_reports.report_card_type_usage, name='report_card_type_usage'),
    path('reports/cards/card-renewal/', views_reports.report_card_renewal, name='report_card_renewal'),
    path('reports/cards/expired-cards/', views_reports.report_expired_cards, name='report_expired_cards'),
    path('reports/cards/consultation-type/', views_reports.report_consultation_type, name='report_consultation_type'),
    path('reports/cards/revenue-by-card-type/', views_reports.report_revenue_by_card_type, name='report_revenue_by_card_type'),
    path('reports/cards/revenue-by-consultation-type/', views_reports.report_revenue_by_consultation_type, name='report_revenue_by_consultation_type'),
    path('reports/cards/department-consultation-stats/', views_reports.report_department_consultation_stats, name='report_department_consultation_stats'),

    # ── Specialization Reports ────────────────────────────────────────────────
    path('reports/specializations/doctors-by-department/', views_reports.report_doctors_by_department, name='report_doctors_by_department'),
    path('reports/specializations/doctors-by-specialization/', views_reports.report_doctors_by_specialization, name='report_doctors_by_specialization'),
    path('reports/specializations/patient-volume/', views_reports.report_patient_volume_by_specialization, name='report_patient_volume_by_specialization'),
    path('reports/specializations/revenue/', views_reports.report_revenue_by_specialization, name='report_revenue_by_specialization'),
    path('reports/specializations/appointment-stats/', views_reports.report_appointment_stats_by_specialization, name='report_appointment_stats_by_specialization'),

    # ── Physical Inventory Count Reports ──────────────────────────────────────
    path('reports/inventory/physical-count/', views_reports.report_physical_count, name='report_physical_count'),
    path('reports/inventory/reconciliation/', views_reports.report_inventory_reconciliation, name='report_inventory_reconciliation'),
    path('reports/inventory/adjustments/', views_reports.report_inventory_adjustments, name='report_inventory_adjustments'),
    path('reports/inventory/opening-balance/', views_reports.report_opening_balance, name='report_opening_balance'),
    path('reports/inventory/closing-balance/', views_reports.report_closing_balance, name='report_closing_balance'),
    path('reports/inventory/annual/', views_reports.report_annual_inventory, name='report_annual_inventory'),
    path('reports/inventory/variance/', views_reports.report_stock_variance, name='report_stock_variance'),
    path('reports/inventory/valuation/', views_reports.report_inventory_valuation_combined, name='report_inventory_valuation_combined'),
    path('reports/inventory/count-history/', views_reports.report_inventory_count_history, name='report_inventory_count_history'),
    path('reports/inventory/audit/', views_reports.report_inventory_audit, name='report_inventory_audit'),

    # ── Surgery & Procedure module ────────────────────────────────────────────
    path('surgery/', views_surgery.surgery_dashboard, name='surgery_dashboard'),
    path('surgery/orders/', views_surgery.surgery_order_list, name='surgery_order_list'),
    path('surgery/orders/new/', views_surgery.surgery_order_create, name='surgery_order_create'),
    path('surgery/orders/new/patient/<int:patient_id>/', views_surgery.surgery_order_create, name='surgery_order_create_patient'),
    path('surgery/orders/new/visit/<int:visit_id>/', views_surgery.surgery_order_create, name='surgery_order_create_visit'),
    path('surgery/orders/<int:order_id>/', views_surgery.surgery_order_detail, name='surgery_order_detail'),
    path('surgery/orders/<int:order_id>/edit/', views_surgery.surgery_order_edit, name='surgery_order_edit'),
    path('surgery/orders/<int:order_id>/status/', views_surgery.surgery_order_update_status, name='surgery_order_update_status'),
    path('surgery/orders/<int:order_id>/schedule/', views_surgery.surgery_schedule_create, name='surgery_schedule_create'),
    path('surgery/orders/<int:order_id>/anesthesia/', views_surgery.surgery_anesthesia_create, name='surgery_anesthesia_create'),
    path('surgery/orders/<int:order_id>/anesthesia/finalize/', views_surgery.surgery_anesthesia_finalize, name='surgery_anesthesia_finalize'),
    path('surgery/orders/<int:order_id>/anesthesia/history/', views_surgery.surgery_anesthesia_history, name='surgery_anesthesia_history'),
    path('surgery/orders/<int:order_id>/anesthesia/print/', views_surgery.surgery_anesthesia_print, name='surgery_anesthesia_print'),
    path('surgery/orders/<int:order_id>/anesthesia/print/<int:version>/', views_surgery.surgery_anesthesia_print, name='surgery_anesthesia_print_version'),
    path('surgery/orders/<int:order_id>/operative-note/', views_surgery.operative_note_create, name='operative_note_create'),
    path('surgery/orders/<int:order_id>/operative-note/finalize/', views_surgery.operative_note_finalize, name='operative_note_finalize'),
    path('surgery/orders/<int:order_id>/operative-note/history/', views_surgery.operative_note_history, name='operative_note_history'),
    path('surgery/orders/<int:order_id>/operative-note/print/', views_surgery.operative_note_print, name='operative_note_print'),
    path('surgery/orders/<int:order_id>/operative-note/print/<int:version>/', views_surgery.operative_note_print, name='operative_note_print_version'),
    path('surgery/orders/<int:order_id>/postop-note/', views_surgery.postop_note_create, name='postop_note_create'),
    path('surgery/orders/<int:order_id>/postop-note/finalize/', views_surgery.postop_note_finalize, name='postop_note_finalize'),
    path('surgery/orders/<int:order_id>/postop-note/history/', views_surgery.postop_note_history, name='postop_note_history'),
    path('surgery/orders/<int:order_id>/postop-note/print/', views_surgery.postop_note_print, name='postop_note_print'),
    path('surgery/orders/<int:order_id>/postop-note/print/<int:version>/', views_surgery.postop_note_print, name='postop_note_print_version'),
    path('surgery/orders/<int:order_id>/nursing-addendum/<str:document_type>/', views_surgery.periop_nursing_addendum_add, name='periop_nursing_addendum_add'),
    path('surgery/orders/<int:order_id>/consumable/', views_surgery.surgery_consumable_add, name='surgery_consumable_add'),
    path('surgery/orders/<int:order_id>/billing/', views_surgery.surgery_billing_generate, name='surgery_billing_generate'),
    # OR Management (surgery module — legacy; use /or/ for full OR scheduling)
    path('surgery/or/', views_surgery.or_dashboard, name='surgery_or_dashboard'),
    path('surgery/or/rooms/', views_surgery.or_room_list, name='surgery_or_room_list'),
    path('surgery/or/rooms/new/', views_surgery.or_room_create, name='surgery_or_room_create'),
    path('surgery/or/rooms/<int:room_id>/edit/', views_surgery.or_room_edit, name='surgery_or_room_edit'),

    # ── Facility & Hospital Location Management ──────────────────────────────
    path('facility/dashboard/', views_facility.facility_dashboard, name='facility_dashboard'),

    path('facility/buildings/', views_facility.building_list, name='building_list'),
    path('facility/buildings/new/', views_facility.building_create, name='building_create'),
    path('facility/buildings/<int:building_id>/edit/', views_facility.building_edit, name='building_edit'),
    path('facility/buildings/<int:building_id>/delete/', views_facility.building_delete, name='building_delete'),

    path('facility/buildings/<int:building_id>/floors/', views_facility.floor_list, name='floor_list'),
    path('facility/buildings/<int:building_id>/floors/new/', views_facility.floor_create, name='floor_create'),
    path('facility/buildings/<int:building_id>/floors/<int:floor_id>/edit/', views_facility.floor_edit, name='floor_edit'),
    path('facility/buildings/<int:building_id>/floors/<int:floor_id>/delete/', views_facility.floor_delete, name='floor_delete'),

    path('facility/wards/', views_facility.ward_list, name='ward_list'),
    path('facility/wards/new/', views_facility.ward_create, name='ward_create'),
    path('facility/wards/<int:ward_id>/', views_facility.ward_detail, name='ward_detail'),
    path('facility/wards/<int:ward_id>/edit/', views_facility.ward_edit, name='ward_edit'),
    path('facility/wards/<int:ward_id>/status/', views_facility.ward_update_status, name='ward_update_status'),

    path('facility/wards/<int:ward_id>/rooms/new/', views_facility.room_create, name='room_create'),
    path('facility/rooms/<int:room_id>/', views_facility.room_detail, name='room_detail'),
    path('facility/rooms/<int:room_id>/edit/', views_facility.room_edit, name='room_edit'),
    path('facility/rooms/<int:room_id>/status/', views_facility.room_update_status, name='room_update_status'),

    path('facility/rooms/<int:room_id>/beds/new/', views_facility.bed_create, name='bed_create'),
    path('facility/beds/<int:bed_id>/edit/', views_facility.bed_edit, name='bed_edit'),
    path('facility/beds/<int:bed_id>/status/', views_facility.bed_update_status, name='bed_update_status'),

    path('facility/admissions/visit/<int:visit_id>/new/', views_facility.admission_create, name='admission_create'),
    path('facility/admissions/<int:admission_id>/transfer/', views_facility.patient_transfer, name='patient_transfer'),
    path('facility/admissions/<int:admission_id>/discharge/', views_facility.patient_discharge, name='patient_discharge'),

    # ── Admission Request & Deposit Management ────────────────────────────────
    path('admissions/dashboard/', views_admissions.admission_dashboard, name='admission_dashboard'),
    path('admissions/requests/', views_admissions.admission_request_list, name='admission_request_list'),
    path('admissions/requests/visit/<int:visit_id>/new/', views_admissions.admission_request_create, name='admission_request_create'),
    path('admissions/requests/<int:req_id>/', views_admissions.admission_request_detail, name='admission_request_detail'),
    path('admissions/requests/<int:req_id>/review/', views_admissions.admission_request_review, name='admission_request_review'),
    path('admissions/requests/<int:req_id>/deposit/credit-approve/', views_admissions.admission_deposit_credit_approve, name='admission_deposit_credit_approve'),
    path('admissions/requests/<int:req_id>/assign-bed/', views_admissions.admission_request_assign_bed, name='admission_request_assign_bed'),
    path('admissions/requests/<int:req_id>/cancel/', views_admissions.admission_request_cancel, name='admission_request_cancel'),
    path('admissions/<int:admission_id>/approve-discharge/', views_admissions.admission_approve_discharge, name='admission_approve_discharge'),
    path('admissions/deposit-rules/', views_admissions.deposit_rule_list, name='deposit_rule_list'),
    path('admissions/deposit-rules/new/', views_admissions.deposit_rule_create, name='deposit_rule_create'),
    path('admissions/deposit-rules/<int:rule_id>/edit/', views_admissions.deposit_rule_edit, name='deposit_rule_edit'),

    # ── Nursing Module ─────────────────────────────────────────────────────────
    path('nursing/dashboard/', views_nursing.nursing_dashboard, name='nursing_dashboard'),
    path('nursing/patients/', views_nursing.nursing_patient_list, name='nursing_patient_list'),
    path('nursing/orders/', views_nursing.nursing_pending_orders, name='nursing_pending_orders'),
    path('nursing/handover/', views_nursing.handover_list, name='nursing_handover_list'),
    path('nursing/handover/new/', views_nursing.handover_create, name='nursing_handover_create'),
    path('nursing/visit/<int:visit_id>/assessment/new/', views_nursing.nursing_assessment_create, name='nursing_assessment_create'),
    path('nursing/visit/<int:visit_id>/pain/new/', views_nursing.pain_assessment_create, name='pain_assessment_create'),
    path('nursing/visit/<int:visit_id>/fall-risk/new/', views_nursing.fall_risk_assessment_create, name='fall_risk_assessment_create'),
    path('nursing/visit/<int:visit_id>/pressure-ulcer/new/', views_nursing.pressure_ulcer_assessment_create, name='pressure_ulcer_assessment_create'),
    path('nursing/visit/<int:visit_id>/nutrition/new/', views_nursing.nutritional_assessment_create, name='nutritional_assessment_create'),
    path('nursing/visit/<int:visit_id>/fluid-balance/new/', views_nursing.fluid_balance_create, name='fluid_balance_create'),
    path('nursing/visit/<int:visit_id>/gcs/new/', views_nursing.gcs_create, name='gcs_create'),
    path('nursing/visit/<int:visit_id>/care-plan/new/', views_nursing.care_plan_create, name='care_plan_create'),
    path('nursing/care-plan/<int:plan_id>/status/', views_nursing.care_plan_update_status, name='care_plan_update_status'),
    path('nursing/visit/<int:visit_id>/consumable/', views_nursing.ward_consumable_use, name='ward_consumable_use'),

    # Procedure Master
    path('surgery/procedures/', views_surgery.procedure_master_list, name='procedure_master_list'),
    path('surgery/procedures/new/', views_surgery.procedure_master_create, name='procedure_master_create'),
    path('surgery/procedures/<int:proc_id>/', views_surgery.procedure_master_detail, name='procedure_master_detail'),
    path('surgery/procedures/<int:proc_id>/edit/', views_surgery.procedure_master_edit, name='procedure_master_edit'),
    # Surgery Reports
    path('surgery/reports/', views_surgery.surgery_reports, name='surgery_reports'),
    path('surgery/reports/schedule/', views_surgery.report_surgery_schedule, name='report_surgery_schedule'),
    path('surgery/reports/completed/', views_surgery.report_completed_surgeries, name='report_completed_surgeries'),
    path('surgery/reports/cancelled/', views_surgery.report_cancelled_surgeries, name='report_cancelled_surgeries'),
    path('surgery/reports/surgeon-performance/', views_surgery.report_surgeon_performance, name='report_surgeon_performance'),
    path('surgery/reports/or-utilization/', views_surgery.report_or_utilization, name='report_or_utilization'),
    path('surgery/reports/or-inventory/', views_surgery.report_or_inventory, name='report_or_inventory'),
    # API endpoints
    path('surgery/api/procedure-info/<int:proc_id>/', views_surgery.api_procedure_info, name='api_procedure_info'),

    # ── Patient Flow module ───────────────────────────────────────────────────
    path('flow/', views_patient_flow.patient_flow_dashboard, name='patient_flow_dashboard'),
    path('flow/visits/', views_patient_flow.patient_flow_list, name='patient_flow_list'),
    path('flow/visits/<int:visit_id>/', views_patient_flow.patient_journey_detail, name='patient_journey_detail'),
    path('flow/visits/<int:visit_id>/status/', views_patient_flow.visit_status_update, name='visit_status_update'),
    path('flow/visits/<int:visit_id>/discharge/', views_patient_flow.discharge_create, name='discharge_create'),
    path('flow/worklist/', views_patient_flow.dept_worklist, name='dept_worklist'),
    path('flow/api/stats/', views_patient_flow.flow_stats_api, name='flow_stats_api'),

    # ── Audit Logs ──────────────────────────────────────────────────────────
    path('audit/', views_audit.audit_dashboard, name='audit_dashboard'),
    path('audit/logs/', views_audit.audit_log_list, name='audit_log_list'),
    path('audit/logs/<int:log_id>/', views_audit.audit_log_detail, name='audit_log_detail'),
    path('audit/reports/user-activity/', views_audit.report_user_activity, name='report_user_activity'),
    path('audit/reports/financial/', views_audit.report_financial_audit, name='report_financial_audit'),
    path('audit/reports/inventory/', views_audit.report_inventory_audit, name='report_inventory_audit'),
    path('audit/reports/patient-access/', views_audit.report_patient_access, name='report_patient_access'),

    # ── Session Management ────────────────────────────────────────────────────
    path('settings/sessions/', views_session.session_dashboard, name='session_dashboard'),
    path('settings/sessions/<int:session_id>/force-logout/', views_session.force_logout, name='force_logout'),
    path('settings/reports/login-history/', views_session.report_login_history, name='report_login_history'),
    path('settings/reports/security/', views_session.report_security, name='report_security'),
    path('settings/reports/user-activity/', views_session.report_user_activity, name='session_report_user_activity'),

    # ── Notifications ─────────────────────────────────────────────────────────
    path('notifications/', views_session.notification_list, name='notification_list'),
    path('notifications/unread-count/', views_session.notifications_unread_count, name='notifications_unread_count'),
    path('notifications/<int:notif_id>/read/', views_session.notification_mark_read, name='notification_mark_read'),
    path('notifications/mark-all-read/', views_session.notification_mark_all_read, name='notification_mark_all_read'),

    # ── OR Scheduling module ─────────────────────────────────────────────────
    path('or/', views_or.or_dashboard, name='or_dashboard'),
    path('or/surgery-requests/', views_or.surgery_request_list, name='surgery_request_list'),
    path('or/surgery-requests/new/', views_or.surgery_request_create, name='surgery_request_create'),
    path('or/surgery-requests/<int:pk>/', views_or.surgery_request_detail, name='surgery_request_detail'),
    path('or/schedule/', views_or.or_schedule_list, name='or_schedule_list'),
    path('or/schedule/new/', views_or.or_schedule_create, name='or_schedule_create'),
    path('or/schedule/<int:pk>/', views_or.or_schedule_detail, name='or_schedule_detail'),
    path('or/schedule/<int:pk>/edit/', views_or.or_schedule_edit, name='or_schedule_edit'),
    path('or/calendar/', views_or.or_calendar, name='or_calendar'),
    path('or/rooms/', views_or.or_room_list, name='or_room_list'),
    path('or/rooms/new/', views_or.or_room_create, name='or_room_create'),
    path('or/rooms/<int:pk>/edit/', views_or.or_room_edit, name='or_room_edit'),
    path('or/check-conflicts/', views_or.check_or_conflicts, name='check_or_conflicts'),
    path('or/api/patient-search/', views_or.patient_search_ajax, name='or_patient_search_ajax'),
    # OR Reports
    path('or/reports/daily/', views_or.report_or_daily, name='report_or_daily'),
    path('or/reports/utilization/', views_or.report_or_utilization, name='report_or_utilization'),
    path('or/reports/surgeon-schedule/', views_or.report_surgeon_schedule, name='report_surgeon_schedule'),
]
